In [10]:
import nltk
import pandas as pd
import numpy as np
import re
from langdetect import detect
from nltk.corpus import stopwords
import re
import string
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
from nltk.corpus import stopwords

In [11]:
df = pd.read_csv('dataSet\jobs_data.csv')

In [12]:
df.head(10)

,Unnamed: 0,title,jobFunction,industry
0,0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi..."
1,1,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services']
2,2,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']"
3,3,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ..."
4,4,Java Technical Lead,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Information Technology ..."
5,5,Technical Support Engineer,"['IT/Software Development', 'Engineering - Tel...","['Information Technology Services', 'Computer ..."
6,6,Senior iOS Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Graphic D..."
7,7,Mechanical Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Enginee..."
8,8,Real Estate Sales Specialist - 10th of Ramadan,['Sales/Retail'],['Real Estate/Property Management']
9,9,School Principal,"['Education/Teaching', 'Administration', 'Oper...",['Education']

In [13]:
df.drop('Unnamed: 0' ,axis = 1 ,inplace = True)

In [14]:
df.tail()

,title,jobFunction,industry
10865,Odoo Developer,"['IT/Software Development', 'Engineering - Tel...","['Real Estate/Property Management', 'Manufactu..."
10866,Senior PHP Developer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...",['Information Technology Services']
10867,Sales & Account Manager (Real Estate / Medical...,"['Business Development', 'Sales/Retail', 'Cust...","['Real Estate/Property Management', 'Retail', ..."
10868,Technical and Network Support Engineer - Alexa...,"['Installation/Maintenance/Repair', 'Engineeri...","['Computer Software', 'Education', 'Healthcare..."
10869,Senior Java Developer,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services']

In [15]:
df.shape

(10870, 3)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 3 columns):
title          10870 non-null object
jobFunction    10870 non-null object
industry       10870 non-null object
dtypes: object(3)
memory usage: 254.8+ KB

In [17]:
df['title'].value_counts( )

Graphic Designer                                               107
Social Media Specialist                                         94
Accountant                                                      86
Digital Marketing Specialist                                    81
Senior iOS Developer                                            74
Sales Account Manager                                           68
Sales Representative                                            66
Sales Executive                                                 55
Business Development Executive                                  53
Senior .Net Developer                                           52
Full Stack Developer                                            51
Sales Engineer                                                  49
Senior Front-End Developer                                      48
Receptionist                                                    47
Account Manager                                                 47
Senior PHP Developer                                            46
Sales Manager                                                   44
Senior Android Developer                                        38
Android Developer                                               38
Senior Graphic Designer                                         35
Customer Service Representative                                 35
Secretary                                                       34
Telesales Agent                                                 34
Sales Specialist                                                33
Front-End Developer                                             32
Property Consultant                                             32
WordPress Developer                                             32
UI/UX Designer                                                  32
Project Manager                                                 31
SEO Specialist                                                  30
                                                              ...
SAP Implementation Project Support Coordinator - Alexandria      1
Sales Engineer - Lighting Field                                  1
Senior Personnel Generalist                                      1
Sales & Marketing Intern                                         1
Data Analyst (CVM/ Insights/ Pricing)                            1
Chief Accountant - Cairo, Egypt                                  1
Activity Teacher - Foreigner                                     1
3D BIM Structural Engineer                                       1
Facility Maintenance Supervisor                                  1
Receptionist - Medical Lab                                       1
Senior Odoo Developer                                            1
Senior Back-End Developer - Symfony                              1
Secretary & Admin Specialist                                     1
Accounting Consultant                                            1
Software Technical Writer                                        1
Food Plant Manager                                               1
Warehouse Manager - Construction Background                      1
Junior Software Quality Control Engineer                         1
Hyperion Planning Consultant                                     1
Technical Support-Gold Account - WE                              1
Marketing Director - Real Estate                                 1
MS Dynamics CRM Leader - Saudi Arabia                            1
Projects Director                                                1
Health & Safety Manager - Sharqia                                1
Computer Programming Instructor                                  1
Ticketing Agent - CCIE Collaboration - Libya                     1
Oracle Database Administrator (DBA)                              1
Hosting & Cloud Presales Engineer                                1
HR Assistant                                                     1
Technical Writer - Freelance                                     1
Name: title, Length: 3230, dtype: int64

In [18]:
len([df['jobFunction'].value_counts()][0])

836

In [19]:
df['jobFunction'].value_counts( )

['IT/Software Development', 'Engineering - Telecom/Technology']                                       1489
['Engineering - Telecom/Technology', 'IT/Software Development']                                       1113
['Sales/Retail']                                                                                       583
['Administration']                                                                                     395
['Accounting/Finance']                                                                                 370
['Education/Teaching']                                                                                 315
['Media/Journalism/Publishing', 'Marketing/PR/Advertising']                                            290
['Marketing/PR/Advertising', 'Media/Journalism/Publishing']                                            277
['Creative/Design/Art']                                                                                243
['Human Resources']                                                                                    211
['Customer Service/Support']                                                                           180
['Customer Service/Support', 'Sales/Retail']                                                           138
['Sales/Retail', 'Customer Service/Support']                                                           137
['Installation/Maintenance/Repair', 'Engineering - Telecom/Technology', 'IT/Software Development']     129
['Engineering - Construction/Civil/Architecture']                                                      122
['Engineering - Mechanical/Electrical']                                                                119
['nan']                                                                                                117
['IT/Software Development']                                                                             98
['IT/Software Development', 'Engineering - Telecom/Technology', 'Quality']                              91
['Marketing/PR/Advertising']                                                                            85
['Quality', 'Engineering - Telecom/Technology', 'IT/Software Development']                              80
['Business Development']                                                                                71
['Education/Teaching', 'Training/Instructor']                                                           62
['Marketing/PR/Advertising', 'Sales/Retail']                                                            61
['Logistics/Supply Chain']                                                                              60
['Installation/Maintenance/Repair', 'Engineering - Mechanical/Electrical']                              58
['Business Development', 'Sales/Retail']                                                                53
['Marketing/PR/Advertising', 'Creative/Design/Art']                                                     52
['Administration', 'Customer Service/Support']                                                          51
['IT/Software Development', 'Installation/Maintenance/Repair', 'Engineering - Telecom/Technology']      50
                                                                                                      ...
['Business Development', 'Engineering - Construction/Civil/Architecture']                                1
['Business Development', 'Sales/Retail', 'Operations/Management']                                        1
['Sales/Retail', 'IT/Software Development', 'Engineering - Mechanical/Electrical']                       1
['Sales/Retail', 'Business Development', 'Marketing/PR/Advertising']                                     1
['Accounting/Finance', 'Strategy/Consulting', 'IT/Software Development']                                 1
['Media/Journalism/Publishing', 'Business Development', 'Sales/Retail']                                  1
['Engineering - Other', 'Installation/Maintenance/Repair']                                               1
['Administration', 'Marketing/PR/Advertising']                                                           1
['Administration', 'Marketing/PR/Advertising', 'Sales/Retail']                                           1
['Operations/Management', 'Sales/Retail', 'Customer Service/Support']                                    1
['Business Development', 'Medical/Healthcare', 'Sales/Retail']                                           1
['Manufacturing/Production', 'Engineering - Mechanical/Electrical', 'Sales/Retail']                      1
['Training/Instructor', 'Creative/Design/Art']                                                           1
['Marketing/PR/Advertising', 'Media/Journalism/Publishing', 'Business Development']                      1
['Accounting/Finance', 'Administration', 'Operations/Management']                                        1
['IT/Software Development', 'Business Development', 'Engineering - Telecom/Technology']                  1
['Sales/Retail', 'Engineering - Telecom/Technology', 'Operations/Management']                            1
['Administration', 'Logistics/Supply Chain']                                                             1
['IT/Software Development', 'Project/Program Management', 'Installation/Maintenance/Repair']             1
['Administration', 'Operations/Management', 'Analyst/Research']                                          1
['Operations/Management', 'Marketing/PR/Advertising', 'Business Development']                            1
['Engineering - Oil & Gas/Energy', 'Engineering - Mechanical/Electrical', 'Sales/Retail']                1
['Operations/Management', 'Engineering - Other', 'Logistics/Supply Chain']                               1
['Manufacturing/Production', 'Logistics/Supply Chain', 'Engineering - Other']                            1
['Operations/Management', 'Engineering - Construction/Civil/Architecture']                               1
['Training/Instructor', 'Engineering - Telecom/Technology', 'IT/Software Development']                   1
['Installation/Maintenance/Repair', 'IT/Software Development', 'Project/Program Management']             1
['Quality', 'R&D/Science', 'Pharmaceutical']                                                             1
['Education/Teaching', 'Pharmaceutical', 'Writing/Editorial']                                            1
['IT/Software Development', 'Customer Service/Support', 'Project/Program Management']                    1
Name: jobFunction, Length: 836, dtype: int64

In [20]:
df['industry'].value_counts( )

['Information Technology Services']                                                                                                1183
['Computer Software']                                                                                                               962
['Marketing and Advertising']                                                                                                       689
['Education']                                                                                                                       536
['Real Estate/Property Management']                                                                                                 460
['Information Technology Services', 'Computer Software']                                                                            445
['Computer Software', 'Information Technology Services']                                                                            404
['Manufacturing']                                                                                                                   298
['Healthcare and Medical Services']                                                                                                 219
['Engineering Services']                                                                                                            164
['Construction - Residential & Commercial/Office']                                                                                  137
['Internet/E-commerce', 'Information Technology Services', 'Computer Software']                                                      79
['Construction - Residential & Commercial/Office', 'Real Estate/Property Management']                                                59
['Internet/E-commerce', 'Information Technology Services', 'Healthcare and Medical Services']                                        52
['Marketing and Advertising', 'Computer Software']                                                                                   51
['Real Estate/Property Management', 'Construction - Residential & Commercial/Office']                                                50
['Information Technology Services', 'Computer and Network Security', 'Computer Software']                                            48
['Computer Software', 'Internet/E-commerce', 'Information Technology Services']                                                      45
['Internet/E-commerce', 'Information Technology Services']                                                                           44
['Engineering Services', 'Manufacturing']                                                                                            43
['Information Technology Services', 'Marketing and Advertising']                                                                     40
['Engineering Services', 'Computer Software']                                                                                        35
['Computer Software', 'Marketing and Advertising']                                                                                   34
['Computer Software', 'Information Technology Services', 'Computer and Network Security']                                            32
['Training and Coaching', 'Education']                                                                                               32
['Internet/E-commerce', 'Computer Software', 'Information Technology Services']                                                      29
['Computer Software', 'Information Technology Services', 'Marketing and Advertising']                                                28
['Human Resources', 'Computer Software']                                                                                             28
['Engineering Services', 'Information Technology Services']                                                                          28
['Information Technology Services', 'Internet/E-commerce', 'Computer Software']                                                      27
                                                                                                                                   ...
['Construction - Residential & Commercial/Office', 'Telecommunications']                                                              1
['Education', 'Real Estate/Property Management']                                                                                      1
['Graphic Design', 'Marketing and Advertising', 'Apparel and Fashion']                                                                1
['Manufacturing', 'Chemicals', 'Construction - Industrial Facilities and Infrastructure']                                             1
['Real Estate/Property Management', 'Architectural and Design Services', 'Engineering Services']                                      1
['Marketing and Advertising', 'Fine Art']                                                                                             1
['Hospitality/Hotels', 'Computer Software', 'Healthcare and Medical Services']                                                        1
['Real Estate/Property Management', 'Marketing and Advertising', 'Publishing and Printing']                                           1
['Engineering Services', 'Oil and Gas']                                                                                               1
['Medical Devices and Supplies', 'FMCG', 'Manufacturing']                                                                             1
['Textile and Clothing', 'Manufacturing', 'Chemicals']                                                                                1
['Information Technology Services', 'Accounting and Auditing Services', 'Retail']                                                     1
['Public Relations and Communications', 'Legal Services', 'Marketing and Advertising']                                                1
['Mining and Metals', 'Engineering Services', 'Manufacturing']                                                                        1
['Computer Software', 'Arts and Crafts', 'Information Technology Services']                                                           1
['Engineering Services', 'Construction - Residential & Commercial/Office', 'Real Estate/Property Management']                         1
['Computer Hardware', 'Computer Software']                                                                                            1
['Engineering Services', 'Research', 'Information Technology Services']                                                               1
['Engineering Services', 'Marketing and Advertising', 'Education']                                                                    1
['Computer and Network Security', 'Computer Networking', 'Computer Software']                                                         1
['Information Technology Services', 'Internet/E-commerce', 'Logistics and Supply Chain']                                              1
['Engineering Services', 'Management Consulting', 'Construction - Residential & Commercial/Office']                                   1
['Architectural and Design Services', 'Construction - Residential & Commercial/Office', 'Recreational Facilities and Services']       1
['Computer Networking', 'Marketing and Advertising', 'Legal Services']                                                                1
['Manufacturing', 'Architectural and Design Services']                                                                                1
['Apparel and Fashion', 'Construction - Residential & Commercial/Office', 'Capital Markets']                                          1
['Consulting Services', 'Business Services - Other', 'Marketing and Advertising']                                                     1
['Consulting Services', 'Education', 'Translation and Localization']                                                                  1
['Engineering Services', 'Hospitality/Hotels', 'Manufacturing']                                                                       1
['Real Estate/Property Management', 'Construction - Residential & Commercial/Office', 'Hospitality/Hotels']                           1
Name: industry, Length: 1523, dtype: int64

### clean Data

In [21]:
stop = stopwords.words('english')
stop_words_ = set(stopwords.words('english'))
wn = WordNetLemmatizer()

def black_txt(token):
    return  token not in stop_words_ and token not in list(string.punctuation)     
  
def clean_txt(text):
    clean_text = []
    clean_text2 = []
    text = re.sub("'", "",text)
    text=re.sub("(\\d|\\W)+"," ",text) 
    text = text.replace("nbsp", "")
    clean_text = [ wn.lemmatize(word, pos="n") for word in word_tokenize(text.lower()) if black_txt(word)]
    clean_text2 = [word for word in clean_text if black_txt(word)]
    return " ".join(clean_text2)

In [22]:
df['jobFunctionTxt'] = df['jobFunction'].apply(clean_txt)
df['titleTxt'] = df['title'].apply(clean_txt)
df['industryTXT'] = df['industry'].apply(clean_txt)

In [23]:
df.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT
0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising
1,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services'],installation maintenance repair software devel...,cisco collaboration specialist engineer,information technology service
2,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']",engineering telecom technology software develo...,senior back end php developer,computer software computer networking
3,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ...",creative design art software development,ux designer,computer software information technology servi...
4,Java Technical Lead,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Information Technology ...",engineering telecom technology software develo...,java technical lead,computer software information technology service

In [24]:
df['titleTxt'].value_counts( )

graphic designer                                 121
social medium specialist                          94
accountant                                        86
digital marketing specialist                      81
senior net developer                              78
senior io developer                               74
sale account manager                              71
full stack developer                              69
sale representative                               69
senior front end developer                        65
sale executive                                    60
front end developer                               54
business development executive                    53
net developer                                     50
sale engineer                                     50
receptionist                                      47
account manager                                   47
sale manager                                      46
senior php developer                              46
senior android developer                          38
android developer                                 38
senior graphic designer                           36
customer service representative                   35
sale specialist                                   35
ui ux designer                                    34
secretary                                         34
telesales agent                                   34
io developer                                      33
property consultant                               32
wordpress developer                               32
                                                ...
database web developer                             1
production engineer furniture                      1
front end developer react                          1
bim discipline lead mechanical                     1
site engineer steel structure                      1
technical office team leader                       1
health safety manager sharqia                      1
warehouse section head                             1
english instructor adult th october part time      1
junior sale representative real estate             1
back end development team leader                   1
student affair manager                             1
production engineer al sadat city                  1
infrastructure specialist                          1
ic design consultant                               1
software developer experienced                     1
front end developer alexandria                     1
hvac system bim engineer                           1
senior safety engineer                             1
front desk admin assistant alexandria              1
junior software tester                             1
elementary english teacher                         1
english content writer                             1
science teacher                                    1
senior hvac engineer                               1
senior data security analyst                       1
technical operation head                           1
accountant damietta                                1
medical sale representative qalubia                1
real estate sale agent mohandessin branch          1
Name: titleTxt, Length: 3118, dtype: int64

In [25]:
df.iloc[93]

title                                                   3D Designer
jobFunction       ['Media/Journalism/Publishing', 'Creative/Desi...
industry                              ['Marketing and Advertising']
jobFunctionTxt     medium journalism publishing creative design art
titleTxt                                                   designer
industryTXT                                   marketing advertising
Name: 93, dtype: object

In [26]:
df['lang'] = df['title'].apply(detect) #detect lang of title column

In [27]:
df

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,lang
0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising,en
1,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services'],installation maintenance repair software devel...,cisco collaboration specialist engineer,information technology service,en
2,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']",engineering telecom technology software develo...,senior back end php developer,computer software computer networking,en
3,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ...",creative design art software development,ux designer,computer software information technology servi...,da
4,Java Technical Lead,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Information Technology ...",engineering telecom technology software develo...,java technical lead,computer software information technology service,en
5,Technical Support Engineer,"['IT/Software Development', 'Engineering - Tel...","['Information Technology Services', 'Computer ...",software development engineering telecom techn...,technical support engineer,information technology service computer software,en
6,Senior iOS Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Graphic D...",engineering telecom technology software develo...,senior io developer,information technology service graphic design ...,en
7,Mechanical Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Enginee...",engineering mechanical electrical,mechanical engineer,architectural design service engineering servi...,en
8,Real Estate Sales Specialist - 10th of Ramadan,['Sales/Retail'],['Real Estate/Property Management'],sale retail,real estate sale specialist th ramadan,real estate property management,en
9,School Principal,"['Education/Teaching', 'Administration', 'Oper...",['Education'],education teaching administration operation ma...,school principal,education,en
10,Senior Sales Representative,"['Sales/Retail', 'Marketing/PR/Advertising', '...",['Marketing and Advertising'],sale retail marketing pr advertising medium jo...,senior sale representative,marketing advertising,ca
11,Accountant,['Accounting/Finance'],['Education'],accounting finance,accountant,education,en
12,Indoor Sales Executive,"['Sales/Retail', 'Creative/Design/Art']","['Architectural and Design Services', 'Manufac...",sale retail creative design art,indoor sale executive,architectural design service manufacturing fur...,en
13,PHP Full-Stack - Joomla Expert,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services'],software development engineering telecom techn...,php full stack joomla expert,information technology service,sv
14,English Teacher Assistant,['Education/Teaching'],['Education'],education teaching,english teacher assistant,education,en
15,Marketing Coordinator,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,marketing coordinator,marketing advertising,en
16,Senior Business Developer,"['Marketing/PR/Advertising', 'Sales/Retail']","['Marketing and Advertising', 'Computer Softwa...",marketing pr advertising sale retail,senior business developer,marketing advertising computer software public...,en
17,Senior Website Developer,"['IT/Software Development', 'Engineering - Tel...","['Insurance', 'Computer Software']",software development engineering telecom techn...,senior website developer,insurance computer software,en
18,Chief Accountant,['Accounting/Finance'],['Education'],accounting finance,chief accountant,education,en
19,Senior Front-End Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Internet/...",engineering telecom technology software develo...,senior front end developer,information technology service internet e comm...,nl
20,Sales Account Manager - Google Cloud,"['IT/Software Development', 'Sales/Retail', 'E...","['Computer Software', 'Information Technology ...",software development sale retail engineering t...,sale account manager google cloud,computer software information technology service,en
21,Senior Back-End Developer,"['IT/Software Development', 'Engineering - Tel...",['Education'],software development engineering telecom techn...,senior back end developer,education,en
22,Video Editor,"['Creative/Design/Art', 'Media/Journalism/Publ...",['Marketing and Advertising'],creative design art medium journalism publishing,video editor,marketing advertising,es
23,Digital Marketing Specialist,['Marketing/PR/Advertising'],['Marketing and Advertising'],marketing pr advertising,digital marketing specialist,marketing advertising,en
24,Mechanical Technical Office Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Constru...",engineering mechanical electrical,mechanical technical office engineer,architectural design service construction resi...,en
25,Sales Engineer,"['IT/Software Development', 'Sales/Retail']","['Information Technology Services', 'Consultin...",software development sale retail,sale engineer,information technology service consulting serv...,af
26,German Teacher - American School,['Education/Teaching'],['Education'],education teaching,german teacher american school,education,en
27,Personal Assistant,['Administration'],"['Real Estate/Property Management', 'Business ...",administration,personal assistant,real estate property management business suppl...,it
28,Sales Account Manager,['Sales/Retail'],"['Logistics and Supply Chain', 'Translation an...",sale retail,sale account manager,logistics supply chain translation localizatio...,en
29,Sales Coordinator/Telesales,"['Administration', 'Operations/Management', 'S...",['Information Technology Services'],administration operation management sale retail,sale coordinator telesales,information technology service,es
...,...,...,...,...,...,...,...
10840,Production Manager - PE Film Extrusion line,"['Manufacturing/Production', 'Engineering - Me...","['Manufacturing', 'Publishing and Printing', '...",manufacturing production engineering mechanica...,production manager pe film extrusion line,manufacturing publishing printing chemical,en
10841,Customer Support Engineer,"['Engineering - Telecom/Technology', 'Engineer...","['Computer Software', 'Information Technology ...",engineering telecom technology engineering mec...,customer support engineer,computer software information technology servi...,en
10842,Nursery Psychologist,['Education/Teaching'],['Education'],education teaching,nursery psychologist,education,en
10843,Managing Director - Kuwait,['Sales/Retail'],['Information Technology Services'],sale retail,managing director kuwait,information technology service,tl
10844,Office Manager,"['Administration', 'Human Resources']",['Manufacturing'],administration human resource,office manager,manufacturing,en
10845,Senior Software Business Analyst,"['IT/Software Development', 'Analyst/Research'...",['Information Technology Services'],software development analyst research engineer...,senior software business analyst,information technology service,en
10846,Public Relations Manager,"['Marketing/PR/Advertising', 'Media/Journalism...","['Human Resources', 'Computer Software']",marketing pr advertising medium journalism pub...,public relation manager,human resource computer software,en
10847,Property Sales Consultant - Real Estate,['Sales/Retail'],['Real Estate/Property Management'],sale retail,property sale consultant real estate,real estate property management,ca
10848,Real Estate Sales Agent,['Sales/Retail'],['Real Estate/Property Management'],sale retail,real estate sale agent,real estate property management,ca
10849,Web Designer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...","['Internet/E-commerce', 'Information Technolog...",engineering telecom technology software develo...,web designer alexandria,internet e commerce information technology ser...,da
10850,Senior Marketing Executive,"['Marketing/PR/Advertising', 'Media/Journalism...","['Marketing and Advertising', 'Real Estate/Pro...",marketing pr advertising medium journalism pub...,senior marketing executive,marketing advertising real estate property man...,en
10851,Outdoor Sales Representative - Alexandria,"['Customer Service/Support', 'Sales/Retail']","['Graphic Design', 'Computer Software', 'Marke...",customer service support sale retail,outdoor sale representative alexandria,graphic design computer software marketing adv...,ca
10852,Front-End Web Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Healthcare and Medical ...",engineering telecom technology software develo...,front end web developer,computer software healthcare medical service,nl
10853,Sales Executive,['Sales/Retail'],"['Information Technology Services', 'Translati...",sale retail,sale executive,information technology service translation loc...,ca
10854,Secretary,['Administration'],['Marketing and Advertising'],administration,secretary,marketing advertising,en
10855,QA Engineer,"['IT/Software Development', 'Quality']","['Engineering Services', 'Computer Software']",software development quality,qa engineer,engineering service computer software,af
10856,Senior .Net Web Developer,"['IT/Software Development', 'Engineering - Tel...",['Computer Software'],software development engineering telecom techn...,senior net web developer,computer software,nl
10857,Property Advisor,['Sales/Retail'],['Real Estate/Property Management'],sale retail,property advisor,real estate property management,en
10858,Pharmacist,['Pharmaceutical'],"['Pharmaceuticals', 'Health, Wellness and Fitn...",pharmaceutical,pharmacist,pharmaceutical health wellness fitness healthc...,en
10859,Arabic KG Teacher - مُدرسة لغة عربية رياض أطفال,['Education/Teaching'],['Education'],education teaching,arabic kg teacher م درسة لغة عربية رياض أطفال,education,ar
10860,"Receptionist, Front Desk Clerk","['Medical/Healthcare', 'Hospitality/Hotels/Foo...","['Hospitality/Hotels', 'Healthcare and Medical...",medical healthcare hospitality hotel food service,receptionist front desk clerk,hospitality hotel healthcare medical service,nl
10861,iOS Developer,"['IT/Software Development', 'Engineering - Tel...","['Computer Software', 'Information Technology ...",software development engineering telecom techn...,io developer,computer software information technology service,nl
10862,Sales Executive,['Sales/Retail'],"['Marketing and Advertising', 'Furniture']",sale retail,sale executive,marketing advertising furniture,ca
10863,Solution Developer / Back-End Developer Subjec...,"['Engineering - Telecom/Technology', 'IT/Softw...",['Computer Software'],engineering telecom technology software develo...,solution developer back end developer subject ...,computer software,en
10864,Marketing Specialist,"['Marketing/PR/Advertising', 'Media/Journalism...","['Marketing and Advertising', 'Public Relation...",marketing pr advertising medium journalism pub...,marketing specialist,marketing advertising public relation communic...,en
10865,Odoo Developer,"['IT/Software Development', 'Engineering - Tel...","['Real Estate/Property Management', 'Manufactu...",software development engineering telecom techn...,odoo developer,real estate property management manufacturing,nl
10866,Senior PHP Developer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...",['Information Technology Services'],engineering telecom technology software develo...,senior php developer alexandria,information technology service,en
10867,Sales & Account Manager (Real Estate / Medical...,"['Business Development', 'Sales/Retail', 'Cust...","['Real Estate/Property Management', 'Retail', ...",business development sale retail customer serv...,sale account manager real estate medical assiut,real estate property management retail healthc...,ca
10868,Technical and Network Support Engineer - Alexa...,"['Installation/Maintenance/Repair', 'Engineeri...","['Computer Software', 'Education', 'Healthcare...",installation maintenance repair engineering te...,technical network support engineer alexandria,computer software education healthcare medical...,en
10869,Senior Java Developer,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services'],software development engineering telecom techn...,senior java developer,information technology service,sl

In [28]:
df['lang'].value_counts( )

en    7343
nl     665
ca     536
ro     386
de     295
it     286
es     246
da     186
af     153
fr     139
id     123
tl     117
no     105
pt      69
sl      63
hr      34
fi      32
ar      21
sv      16
pl      16
et      15
tr      11
cy       6
lt       2
so       2
sw       2
hu       1
Name: lang, dtype: int64

In [29]:
df_AR = df.loc[df['lang'] == 'ar']
df_AR.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,lang
136,معلم لغة عربية,['Education/Teaching'],['Education'],education teaching,معلم لغة عربية,education,ar
551,Concrete Block Plant Operator - مشغل محطة طوب ...,['nan'],['Construction - Residential & Commercial/Offi...,nan,concrete block plant operator مشغل محطة طوب اس...,construction residential commercial office rea...,ar
1282,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Information Technology Services', 'Accountin...",legal,legal affair officer مسئول الشئون القانونية,information technology service accounting audi...,ar
1297,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Computer Software', 'Accounting and Auditing...",legal,legal affair officer مسئول الشئون القانونية,computer software accounting auditing service ...,ar
1467,Advertising Production Manager - مدير انتاج في...,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,advertising production manager مدير انتاج في م...,marketing advertising,ar

### Translate Arabic title to English

In [30]:
from textblob import TextBlob
def translate_AR_EN(word0):
    word = TextBlob('{0}'.format(word0) )
    try:
        e = word.translate(from_lang = 'ar' , to = 'en')
    except:
        e = word
    return e

In [31]:
df_AR['titleTxt'] = df_AR['titleTxt'].apply(translate_AR_EN)

C:\Users\elnafad\Anaconda4\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
df_AR.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,lang
136,معلم لغة عربية,['Education/Teaching'],['Education'],education teaching,"(A, r, a, b, i, c, , t, e, a, c, h, e, r)",education,ar
551,Concrete Block Plant Operator - مشغل محطة طوب ...,['nan'],['Construction - Residential & Commercial/Offi...,nan,"(c, o, n, c, r, e, t, e, , b, l, o, c, k, , ...",construction residential commercial office rea...,ar
1282,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Information Technology Services', 'Accountin...",legal,"(l, e, g, a, l, , a, f, f, a, i, r, , o, f, ...",information technology service accounting audi...,ar
1297,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Computer Software', 'Accounting and Auditing...",legal,"(l, e, g, a, l, , a, f, f, a, i, r, , o, f, ...",computer software accounting auditing service ...,ar
1467,Advertising Production Manager - مدير انتاج في...,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,"(a, d, v, e, r, t, i, s, i, n, g, , p, r, o, ...",marketing advertising,ar

In [33]:
df_AR['titleTxt' ] = df_AR['titleTxt' ].apply(''.join)

C:\Users\elnafad\Anaconda4\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [34]:
df_AR.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,lang
136,معلم لغة عربية,['Education/Teaching'],['Education'],education teaching,Arabic teacher,education,ar
551,Concrete Block Plant Operator - مشغل محطة طوب ...,['nan'],['Construction - Residential & Commercial/Offi...,nan,concrete block plant operator Elameen Cement B...,construction residential commercial office rea...,ar
1282,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Information Technology Services', 'Accountin...",legal,legal affair officer,information technology service accounting audi...,ar
1297,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Computer Software', 'Accounting and Auditing...",legal,legal affair officer,computer software accounting auditing service ...,ar
1467,Advertising Production Manager - مدير انتاج في...,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,advertising production manager A production ma...,marketing advertising,ar

In [35]:
df.loc[df['lang'] == 'ar'].shape

(21, 7)

In [36]:
df_AR.shape

(21, 7)

In [37]:
df.loc[df['lang'] == 'ar'] = df_AR

In [38]:
df

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,lang
0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising,en
1,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services'],installation maintenance repair software devel...,cisco collaboration specialist engineer,information technology service,en
2,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']",engineering telecom technology software develo...,senior back end php developer,computer software computer networking,en
3,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ...",creative design art software development,ux designer,computer software information technology servi...,da
4,Java Technical Lead,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Information Technology ...",engineering telecom technology software develo...,java technical lead,computer software information technology service,en
5,Technical Support Engineer,"['IT/Software Development', 'Engineering - Tel...","['Information Technology Services', 'Computer ...",software development engineering telecom techn...,technical support engineer,information technology service computer software,en
6,Senior iOS Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Graphic D...",engineering telecom technology software develo...,senior io developer,information technology service graphic design ...,en
7,Mechanical Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Enginee...",engineering mechanical electrical,mechanical engineer,architectural design service engineering servi...,en
8,Real Estate Sales Specialist - 10th of Ramadan,['Sales/Retail'],['Real Estate/Property Management'],sale retail,real estate sale specialist th ramadan,real estate property management,en
9,School Principal,"['Education/Teaching', 'Administration', 'Oper...",['Education'],education teaching administration operation ma...,school principal,education,en
10,Senior Sales Representative,"['Sales/Retail', 'Marketing/PR/Advertising', '...",['Marketing and Advertising'],sale retail marketing pr advertising medium jo...,senior sale representative,marketing advertising,ca
11,Accountant,['Accounting/Finance'],['Education'],accounting finance,accountant,education,en
12,Indoor Sales Executive,"['Sales/Retail', 'Creative/Design/Art']","['Architectural and Design Services', 'Manufac...",sale retail creative design art,indoor sale executive,architectural design service manufacturing fur...,en
13,PHP Full-Stack - Joomla Expert,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services'],software development engineering telecom techn...,php full stack joomla expert,information technology service,sv
14,English Teacher Assistant,['Education/Teaching'],['Education'],education teaching,english teacher assistant,education,en
15,Marketing Coordinator,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,marketing coordinator,marketing advertising,en
16,Senior Business Developer,"['Marketing/PR/Advertising', 'Sales/Retail']","['Marketing and Advertising', 'Computer Softwa...",marketing pr advertising sale retail,senior business developer,marketing advertising computer software public...,en
17,Senior Website Developer,"['IT/Software Development', 'Engineering - Tel...","['Insurance', 'Computer Software']",software development engineering telecom techn...,senior website developer,insurance computer software,en
18,Chief Accountant,['Accounting/Finance'],['Education'],accounting finance,chief accountant,education,en
19,Senior Front-End Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Internet/...",engineering telecom technology software develo...,senior front end developer,information technology service internet e comm...,nl
20,Sales Account Manager - Google Cloud,"['IT/Software Development', 'Sales/Retail', 'E...","['Computer Software', 'Information Technology ...",software development sale retail engineering t...,sale account manager google cloud,computer software information technology service,en
21,Senior Back-End Developer,"['IT/Software Development', 'Engineering - Tel...",['Education'],software development engineering telecom techn...,senior back end developer,education,en
22,Video Editor,"['Creative/Design/Art', 'Media/Journalism/Publ...",['Marketing and Advertising'],creative design art medium journalism publishing,video editor,marketing advertising,es
23,Digital Marketing Specialist,['Marketing/PR/Advertising'],['Marketing and Advertising'],marketing pr advertising,digital marketing specialist,marketing advertising,en
24,Mechanical Technical Office Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Constru...",engineering mechanical electrical,mechanical technical office engineer,architectural design service construction resi...,en
25,Sales Engineer,"['IT/Software Development', 'Sales/Retail']","['Information Technology Services', 'Consultin...",software development sale retail,sale engineer,information technology service consulting serv...,af
26,German Teacher - American School,['Education/Teaching'],['Education'],education teaching,german teacher american school,education,en
27,Personal Assistant,['Administration'],"['Real Estate/Property Management', 'Business ...",administration,personal assistant,real estate property management business suppl...,it
28,Sales Account Manager,['Sales/Retail'],"['Logistics and Supply Chain', 'Translation an...",sale retail,sale account manager,logistics supply chain translation localizatio...,en
29,Sales Coordinator/Telesales,"['Administration', 'Operations/Management', 'S...",['Information Technology Services'],administration operation management sale retail,sale coordinator telesales,information technology service,es
...,...,...,...,...,...,...,...
10840,Production Manager - PE Film Extrusion line,"['Manufacturing/Production', 'Engineering - Me...","['Manufacturing', 'Publishing and Printing', '...",manufacturing production engineering mechanica...,production manager pe film extrusion line,manufacturing publishing printing chemical,en
10841,Customer Support Engineer,"['Engineering - Telecom/Technology', 'Engineer...","['Computer Software', 'Information Technology ...",engineering telecom technology engineering mec...,customer support engineer,computer software information technology servi...,en
10842,Nursery Psychologist,['Education/Teaching'],['Education'],education teaching,nursery psychologist,education,en
10843,Managing Director - Kuwait,['Sales/Retail'],['Information Technology Services'],sale retail,managing director kuwait,information technology service,tl
10844,Office Manager,"['Administration', 'Human Resources']",['Manufacturing'],administration human resource,office manager,manufacturing,en
10845,Senior Software Business Analyst,"['IT/Software Development', 'Analyst/Research'...",['Information Technology Services'],software development analyst research engineer...,senior software business analyst,information technology service,en
10846,Public Relations Manager,"['Marketing/PR/Advertising', 'Media/Journalism...","['Human Resources', 'Computer Software']",marketing pr advertising medium journalism pub...,public relation manager,human resource computer software,en
10847,Property Sales Consultant - Real Estate,['Sales/Retail'],['Real Estate/Property Management'],sale retail,property sale consultant real estate,real estate property management,ca
10848,Real Estate Sales Agent,['Sales/Retail'],['Real Estate/Property Management'],sale retail,real estate sale agent,real estate property management,ca
10849,Web Designer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...","['Internet/E-commerce', 'Information Technolog...",engineering telecom technology software develo...,web designer alexandria,internet e commerce information technology ser...,da
10850,Senior Marketing Executive,"['Marketing/PR/Advertising', 'Media/Journalism...","['Marketing and Advertising', 'Real Estate/Pro...",marketing pr advertising medium journalism pub...,senior marketing executive,marketing advertising real estate property man...,en
10851,Outdoor Sales Representative - Alexandria,"['Customer Service/Support', 'Sales/Retail']","['Graphic Design', 'Computer Software', 'Marke...",customer service support sale retail,outdoor sale representative alexandria,graphic design computer software marketing adv...,ca
10852,Front-End Web Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Healthcare and Medical ...",engineering telecom technology software develo...,front end web developer,computer software healthcare medical service,nl
10853,Sales Executive,['Sales/Retail'],"['Information Technology Services', 'Translati...",sale retail,sale executive,information technology service translation loc...,ca
10854,Secretary,['Administration'],['Marketing and Advertising'],administration,secretary,marketing advertising,en
10855,QA Engineer,"['IT/Software Development', 'Quality']","['Engineering Services', 'Computer Software']",software development quality,qa engineer,engineering service computer software,af
10856,Senior .Net Web Developer,"['IT/Software Development', 'Engineering - Tel...",['Computer Software'],software development engineering telecom techn...,senior net web developer,computer software,nl
10857,Property Advisor,['Sales/Retail'],['Real Estate/Property Management'],sale retail,property advisor,real estate property management,en
10858,Pharmacist,['Pharmaceutical'],"['Pharmaceuticals', 'Health, Wellness and Fitn...",pharmaceutical,pharmacist,pharmaceutical health wellness fitness healthc...,en
10859,Arabic KG Teacher - مُدرسة لغة عربية رياض أطفال,['Education/Teaching'],['Education'],education teaching,"arabic kg teacher Arabic teacher, kindergarten",education,ar
10860,"Receptionist, Front Desk Clerk","['Medical/Healthcare', 'Hospitality/Hotels/Foo...","['Hospitality/Hotels', 'Healthcare and Medical...",medical healthcare hospitality hotel food service,receptionist front desk clerk,hospitality hotel healthcare medical service,nl
10861,iOS Developer,"['IT/Software Development', 'Engineering - Tel...","['Computer Software', 'Information Technology ...",software development engineering telecom techn...,io developer,computer software information technology service,nl
10862,Sales Executive,['Sales/Retail'],"['Marketing and Advertising', 'Furniture']",sale retail,sale executive,marketing advertising furniture,ca
10863,Solution Developer / Back-End Developer Subjec...,"['Engineering - Telecom/Technology', 'IT/Softw...",['Computer Software'],engineering telecom technology software develo...,solution developer back end developer subject ...,computer software,en
10864,Marketing Specialist,"['Marketing/PR/Advertising', 'Media/Journalism...","['Marketing and Advertising', 'Public Relation...",marketing pr advertising medium journalism pub...,marketing specialist,marketing advertising public relation communic...,en
10865,Odoo Developer,"['IT/Software Development', 'Engineering - Tel...","['Real Estate/Property Management', 'Manufactu...",software development engineering telecom techn...,odoo developer,real estate property management manufacturing,nl
10866,Senior PHP Developer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...",['Information Technology Services'],engineering telecom technology software develo...,senior php developer alexandria,information technology service,en
10867,Sales & Account Manager (Real Estate / Medical...,"['Business Development', 'Sales/Retail', 'Cust...","['Real Estate/Property Management', 'Retail', ...",business development sale retail customer serv...,sale account manager real estate medical assiut,real estate property management retail healthc...,ca
10868,Technical and Network Support Engineer - Alexa...,"['Installation/Maintenance/Repair', 'Engineeri...","['Computer Software', 'Education', 'Healthcare...",installation maintenance repair engineering te...,technical network support engineer alexandria,computer software education healthcare medical...,en
10869,Senior Java Developer,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services'],software development engineering telecom techn...,senior java developer,information technology service,sl

In [39]:
df.loc[df['lang'] == 'ar']

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,lang
136,معلم لغة عربية,['Education/Teaching'],['Education'],education teaching,Arabic teacher,education,ar
551,Concrete Block Plant Operator - مشغل محطة طوب ...,['nan'],['Construction - Residential & Commercial/Offi...,nan,concrete block plant operator Elameen Cement B...,construction residential commercial office rea...,ar
1282,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Information Technology Services', 'Accountin...",legal,legal affair officer,information technology service accounting audi...,ar
1297,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Computer Software', 'Accounting and Auditing...",legal,legal affair officer,computer software accounting auditing service ...,ar
1467,Advertising Production Manager - مدير انتاج في...,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,advertising production manager A production ma...,marketing advertising,ar
1668,موظفة نشر و سوشيال ميديا اونلاين,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,Publishing and social media employee online,marketing advertising,ar
1996,مندوب مبيعات - خارجي,['Sales/Retail'],"['Computer Software', 'Graphic Design', 'Marke...",sale retail,External sales representative,computer software graphic design marketing adv...,ar
2290,مندوب مبيعات - خارجي,['Sales/Retail'],"['Marketing and Advertising', 'Computer Softwa...",sale retail,External sales representative,marketing advertising computer software graphi...,ar
3179,Legal Affairs Officer - مسئول الشئون القانونية,['Legal'],"['Accounting and Auditing Services', 'Informat...",legal,legal affair officer,accounting auditing service information techno...,ar
3530,Advertising Production Manager - مدير انتاج في...,"['Marketing/PR/Advertising', 'Media/Journalism...",['Marketing and Advertising'],marketing pr advertising medium journalism pub...,advertising production manager A production ma...,marketing advertising,ar
4507,مندوب مبيعات - خارجي,['Sales/Retail'],"['Graphic Design', 'Computer Software', 'Marke...",sale retail,External sales representative,graphic design computer software marketing adv...,ar
4865,معلم لغة عربية,['Education/Teaching'],['Education'],education teaching,Arabic teacher,education,ar
7055,موظفة نشر و سوشيال ميديا اونلاين,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,Publishing and social media employee online,marketing advertising,ar
7607,مندوب مبيعات - خارجي,['Sales/Retail'],"['Computer Software', 'Graphic Design', 'Marke...",sale retail,External sales representative,computer software graphic design marketing adv...,ar
8514,موظفة نشر و سوشيال ميديا اونلاين,"['Marketing/PR/Advertising', 'Media/Journalism...",['Marketing and Advertising'],marketing pr advertising medium journalism pub...,Publishing and social media employee online,marketing advertising,ar
9094,معلم لغة عربية,['Education/Teaching'],['Education'],education teaching,Arabic teacher,education,ar
9303,موظفة نشر و سوشيال ميديا اونلاين,"['Marketing/PR/Advertising', 'Media/Journalism...",['Marketing and Advertising'],marketing pr advertising medium journalism pub...,Publishing and social media employee online,marketing advertising,ar
9804,Arabic KG Teacher - مُدرسة لغة عربية رياض أطفال,['Education/Teaching'],['Education'],education teaching,"arabic kg teacher Arabic teacher, kindergarten",education,ar
10171,موظفة نشر و سوشيال ميديا اونلاين,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,Publishing and social media employee online,marketing advertising,ar
10629,مندوب مبيعات - خارجي,['Sales/Retail'],"['Graphic Design', 'Computer Software', 'Marke...",sale retail,External sales representative,graphic design computer software marketing adv...,ar
10859,Arabic KG Teacher - مُدرسة لغة عربية رياض أطفال,['Education/Teaching'],['Education'],education teaching,"arabic kg teacher Arabic teacher, kindergarten",education,ar

In [40]:
df.drop('lang' ,axis = 1 ,inplace = True)

In [41]:
df.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT
0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising
1,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services'],installation maintenance repair software devel...,cisco collaboration specialist engineer,information technology service
2,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']",engineering telecom technology software develo...,senior back end php developer,computer software computer networking
3,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ...",creative design art software development,ux designer,computer software information technology servi...
4,Java Technical Lead,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Information Technology ...",engineering telecom technology software develo...,java technical lead,computer software information technology service

### Handling Rows With NAN Value
*we have nan value at jopFunction column to handle it:*
if this jobFunction 'which has nan' its title value only one in df drop it,
else search about title(1) has the same title'which its jobFunction has nan' and
assign jobFunction'which has nan' by jobFunction of title(1)

In [42]:
df['jobFunction'].loc[df['jobFunctionTxt'] == 'nan'].count() #count of nan value in dataset

117

In [43]:
df.loc[df['jobFunctionTxt'] == 'nan']

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT
69,Finishing Foreman,['nan'],['Construction - Residential & Commercial/Offi...,nan,finishing foreman,construction residential commercial office rea...
148,Site Accountant,['nan'],"['Engineering Services', 'Construction - Resid...",nan,site accountant,engineering service construction residential c...
303,Finance Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,finance manager,construction residential commercial office tra...
378,Chief Accountant,['nan'],['Construction - Residential & Commercial/Offi...,nan,chief accountant,construction residential commercial office rea...
517,Sales Representative - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,nan,sale representative real estate,construction residential commercial office rea...
551,Concrete Block Plant Operator - مشغل محطة طوب ...,['nan'],['Construction - Residential & Commercial/Offi...,nan,concrete block plant operator Elameen Cement B...,construction residential commercial office rea...
651,BMS Projects Electrical Engineer/ Alexandria,['nan'],['Construction - Residential & Commercial/Offi...,nan,bm project electrical engineer alexandria,construction residential commercial office rea...
718,Technical Office Engineer/ Civil,['nan'],['Construction - Residential & Commercial/Offi...,nan,technical office engineer civil,construction residential commercial office con...
820,Human Resources Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,human resource manager,construction residential commercial office tel...
894,Sales Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,sale manager,construction residential commercial office
1001,Structural Engineer - Combustion Equipment & B...,['nan'],['Construction - Residential & Commercial/Offi...,nan,structural engineer combustion equipment boile...,construction residential commercial office
1116,Purchasing Specialist,['nan'],['Construction - Residential & Commercial/Offi...,nan,purchasing specialist,construction residential commercial office con...
1187,Real Estate Marketing Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,real estate marketing manager,construction residential commercial office
1344,Planning Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,planning engineer,construction residential commercial office con...
1411,Senior Technical Office Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,senior technical office mechanical engineer,construction residential commercial office
1485,Site Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,site manager,construction residential commercial office
1599,Graphic Designer,['nan'],['Construction - Residential & Commercial/Offi...,nan,graphic designer,construction residential commercial office rea...
1675,Food Plant Manager,['nan'],"['Architectural and Design Services', 'Constru...",nan,food plant manager,architectural design service construction indu...
1831,Senior Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,senior site engineer,construction residential commercial office rea...
1872,Senior Sanitary Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,senior sanitary engineer,construction residential commercial office rea...
2019,Site Engineer - Architecture / Civil Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,site engineer architecture civil engineer,construction residential commercial office
2098,Technical Office Team Leader,['nan'],['Construction - Residential & Commercial/Offi...,nan,technical office team leader,construction residential commercial office
2214,Senior General Accountant,['nan'],['Construction - Residential & Commercial/Offi...,nan,senior general accountant,construction residential commercial office rea...
2253,Store Supervisor,['nan'],['Construction - Residential & Commercial/Offi...,nan,store supervisor,construction residential commercial office int...
2411,Purchasing Specialist,['nan'],['Construction - Residential & Commercial/Offi...,nan,purchasing specialist,construction residential commercial office
2483,Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,site engineer,construction residential commercial office
2592,Constructional Engineer,['nan'],"['Architectural and Design Services', 'Constru...",nan,constructional engineer,architectural design service construction resi...
2631,Project Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,project manager,construction residential commercial office
2783,Content Developer - Vocational Education,['nan'],"['Architectural and Design Services', 'Educati...",nan,content developer vocational education,architectural design service education constru...
2860,Contact Center Agent,['nan'],['Construction - Residential & Commercial/Offi...,nan,contact center agent,construction residential commercial office rea...
...,...,...,...,...,...,...
8207,Civil Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,civil site engineer,construction residential commercial office con...
8282,Quality Control Specialist - Chemist,['nan'],['Construction - Residential & Commercial/Offi...,nan,quality control specialist chemist,construction residential commercial office man...
8354,Finance Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,finance manager,construction residential commercial office ret...
8425,Projects Director Engineer - COO,['nan'],"['Engineering Services', 'Construction - Resid...",nan,project director engineer coo,engineering service construction residential c...
8503,Site Finishing Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,site finishing engineer,construction residential commercial office
8614,Site Engineer,['nan'],"['Engineering Services', 'Architectural and De...",nan,site engineer,engineering service architectural design servi...
8654,Technical Office Finishing Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,technical office finishing engineer,construction residential commercial office
8755,Technical Office Engineer - Electrical,['nan'],['Construction - Residential & Commercial/Offi...,nan,technical office engineer electrical,construction residential commercial office con...
8828,Electrical Technical Office Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,electrical technical office engineer,construction residential commercial office con...
8939,Technical Office Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,technical office mechanical engineer,construction residential commercial office
9049,Site Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,site mechanical engineer,construction residential commercial office
9123,Site Electrical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,site electrical engineer,construction residential commercial office
9198,Warehouse Operative,['nan'],['Construction - Residential & Commercial/Offi...,nan,warehouse operative,construction residential commercial office con...
9274,Accounting Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,accounting manager,construction residential commercial office
9386,Site Civil Engineer - Industrial Mega Projects,['nan'],['Construction - Residential & Commercial/Offi...,nan,site civil engineer industrial mega project,construction residential commercial office
9456,Accounting Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,accounting manager,construction residential commercial office rea...
9571,Electro-Mechanical Procurement Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,electro mechanical procurement engineer,construction residential commercial office hos...
9643,Architect/ Interior Designer,['nan'],"['Architectural and Design Services', 'Constru...",nan,architect interior designer,architectural design service construction resi...
9748,Technical Drive Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,technical drive engineer,construction residential commercial office
9864,Senior HVAC Engineer,['nan'],['Construction - Residential & Commercial/Offi...,nan,senior hvac engineer,construction residential commercial office hos...
9895,Facade Surveyor,['nan'],['Construction - Residential & Commercial/Offi...,nan,facade surveyor,construction residential commercial office con...
9998,Document Controller,['nan'],['Construction - Residential & Commercial/Offi...,nan,document controller,construction residential commercial office con...
10104,Receivable Accountant,['nan'],"['Architectural and Design Services', 'Recreat...",nan,receivable accountant,architectural design service recreational faci...
10174,Digital Marketing Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,digital marketing manager,construction residential commercial office rea...
10312,Sales Representative,['nan'],['Construction - Residential & Commercial/Offi...,nan,sale representative,construction residential commercial office rea...
10381,Leasing Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,leasing manager,construction residential commercial office rea...
10521,Specialty Leasing Manager,['nan'],['Construction - Residential & Commercial/Offi...,nan,specialty leasing manager,construction residential commercial office rea...
10558,Social Media Specialist - Mohandessin,['nan'],['Construction - Residential & Commercial/Offi...,nan,social medium specialist mohandessin,construction residential commercial office rea...
10738,Sales Executive - B2B,['nan'],"['Engineering Services', 'Architectural and De...",nan,sale executive b b,engineering service architectural design servi...
10774,General Accountant,['nan'],['Construction - Residential & Commercial/Offi...,nan,general accountant,construction residential commercial office rea...

In [44]:
df['jobFunctionTxt'].replace('nan', np.nan , inplace = True)
null_df = df.loc[df['jobFunctionTxt'].isnull()]
null_df.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT
69,Finishing Foreman,['nan'],['Construction - Residential & Commercial/Offi...,NaN,finishing foreman,construction residential commercial office rea...
148,Site Accountant,['nan'],"['Engineering Services', 'Construction - Resid...",NaN,site accountant,engineering service construction residential c...
303,Finance Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,finance manager,construction residential commercial office tra...
378,Chief Accountant,['nan'],['Construction - Residential & Commercial/Offi...,NaN,chief accountant,construction residential commercial office rea...
517,Sales Representative - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,NaN,sale representative real estate,construction residential commercial office rea...

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10870 entries, 0 to 10869
Data columns (total 6 columns):
title             10870 non-null object
jobFunction       10870 non-null object
industry          10870 non-null object
jobFunctionTxt    10753 non-null object
titleTxt          10870 non-null object
industryTXT       10870 non-null object
dtypes: object(6)
memory usage: 509.6+ KB

In [46]:
df.dropna(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10753 entries, 0 to 10869
Data columns (total 6 columns):
title             10753 non-null object
jobFunction       10753 non-null object
industry          10753 non-null object
jobFunctionTxt    10753 non-null object
titleTxt          10753 non-null object
industryTXT       10753 non-null object
dtypes: object(6)
memory usage: 588.1+ KB

In [47]:
null_df.shape

(117, 6)

In [48]:
df['titleTxt'].iloc[1467-116]

'english instructor alexandria'

In [49]:
l=null_df['industry'].isin(df['industry'])

In [50]:
null_df['eq'] = l

C:\Users\elnafad\Anaconda4\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [51]:
null_df.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,eq
69,Finishing Foreman,['nan'],['Construction - Residential & Commercial/Offi...,NaN,finishing foreman,construction residential commercial office rea...,True
148,Site Accountant,['nan'],"['Engineering Services', 'Construction - Resid...",NaN,site accountant,engineering service construction residential c...,True
303,Finance Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,finance manager,construction residential commercial office tra...,False
378,Chief Accountant,['nan'],['Construction - Residential & Commercial/Offi...,NaN,chief accountant,construction residential commercial office rea...,True
517,Sales Representative - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,NaN,sale representative real estate,construction residential commercial office rea...,True

In [52]:
null_df['eq'].value_counts( )

True     100
False     17
Name: eq, dtype: int64

In [53]:
null_df = null_df[null_df['eq'] != False]

In [54]:
null_df

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,eq
69,Finishing Foreman,['nan'],['Construction - Residential & Commercial/Offi...,NaN,finishing foreman,construction residential commercial office rea...,True
148,Site Accountant,['nan'],"['Engineering Services', 'Construction - Resid...",NaN,site accountant,engineering service construction residential c...,True
378,Chief Accountant,['nan'],['Construction - Residential & Commercial/Offi...,NaN,chief accountant,construction residential commercial office rea...,True
517,Sales Representative - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,NaN,sale representative real estate,construction residential commercial office rea...,True
651,BMS Projects Electrical Engineer/ Alexandria,['nan'],['Construction - Residential & Commercial/Offi...,NaN,bm project electrical engineer alexandria,construction residential commercial office rea...,True
718,Technical Office Engineer/ Civil,['nan'],['Construction - Residential & Commercial/Offi...,NaN,technical office engineer civil,construction residential commercial office con...,True
894,Sales Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,sale manager,construction residential commercial office,True
1001,Structural Engineer - Combustion Equipment & B...,['nan'],['Construction - Residential & Commercial/Offi...,NaN,structural engineer combustion equipment boile...,construction residential commercial office,True
1116,Purchasing Specialist,['nan'],['Construction - Residential & Commercial/Offi...,NaN,purchasing specialist,construction residential commercial office con...,True
1187,Real Estate Marketing Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,real estate marketing manager,construction residential commercial office,True
1411,Senior Technical Office Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,senior technical office mechanical engineer,construction residential commercial office,True
1485,Site Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site manager,construction residential commercial office,True
1599,Graphic Designer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,graphic designer,construction residential commercial office rea...,True
1675,Food Plant Manager,['nan'],"['Architectural and Design Services', 'Constru...",NaN,food plant manager,architectural design service construction indu...,True
1831,Senior Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,senior site engineer,construction residential commercial office rea...,True
1872,Senior Sanitary Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,senior sanitary engineer,construction residential commercial office rea...,True
2019,Site Engineer - Architecture / Civil Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site engineer architecture civil engineer,construction residential commercial office,True
2098,Technical Office Team Leader,['nan'],['Construction - Residential & Commercial/Offi...,NaN,technical office team leader,construction residential commercial office,True
2214,Senior General Accountant,['nan'],['Construction - Residential & Commercial/Offi...,NaN,senior general accountant,construction residential commercial office rea...,True
2253,Store Supervisor,['nan'],['Construction - Residential & Commercial/Offi...,NaN,store supervisor,construction residential commercial office int...,True
2411,Purchasing Specialist,['nan'],['Construction - Residential & Commercial/Offi...,NaN,purchasing specialist,construction residential commercial office,True
2483,Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site engineer,construction residential commercial office,True
2592,Constructional Engineer,['nan'],"['Architectural and Design Services', 'Constru...",NaN,constructional engineer,architectural design service construction resi...,True
2631,Project Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,project manager,construction residential commercial office,True
2860,Contact Center Agent,['nan'],['Construction - Residential & Commercial/Offi...,NaN,contact center agent,construction residential commercial office rea...,True
2976,Marketing Specialist - Curtains,['nan'],['Construction - Residential & Commercial/Offi...,NaN,marketing specialist curtain,construction residential commercial office con...,True
3092,Electrical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,electrical engineer,construction residential commercial office,True
3248,Document Control,['nan'],"['Architectural and Design Services', 'Constru...",NaN,document control,architectural design service construction resi...,True
3322,Executive Architectural Project Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,executive architectural project manager,construction residential commercial office,True
3397,Architecture Technical Office Engineer on Site,['nan'],['Construction - Residential & Commercial/Offi...,NaN,architecture technical office engineer site,construction residential commercial office,True
...,...,...,...,...,...,...,...
7923,Agriculture Engineer - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,NaN,agriculture engineer real estate,construction residential commercial office,True
7992,Projects Sales Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,project sale engineer,construction residential commercial office,True
8167,Warehouse Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,warehouse manager,construction residential commercial office con...,True
8282,Quality Control Specialist - Chemist,['nan'],['Construction - Residential & Commercial/Offi...,NaN,quality control specialist chemist,construction residential commercial office man...,True
8354,Finance Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,finance manager,construction residential commercial office ret...,True
8503,Site Finishing Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site finishing engineer,construction residential commercial office,True
8614,Site Engineer,['nan'],"['Engineering Services', 'Architectural and De...",NaN,site engineer,engineering service architectural design servi...,True
8654,Technical Office Finishing Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,technical office finishing engineer,construction residential commercial office,True
8755,Technical Office Engineer - Electrical,['nan'],['Construction - Residential & Commercial/Offi...,NaN,technical office engineer electrical,construction residential commercial office con...,True
8828,Electrical Technical Office Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,electrical technical office engineer,construction residential commercial office con...,True
8939,Technical Office Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,technical office mechanical engineer,construction residential commercial office,True
9049,Site Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site mechanical engineer,construction residential commercial office,True
9123,Site Electrical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site electrical engineer,construction residential commercial office,True
9198,Warehouse Operative,['nan'],['Construction - Residential & Commercial/Offi...,NaN,warehouse operative,construction residential commercial office con...,True
9274,Accounting Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,accounting manager,construction residential commercial office,True
9386,Site Civil Engineer - Industrial Mega Projects,['nan'],['Construction - Residential & Commercial/Offi...,NaN,site civil engineer industrial mega project,construction residential commercial office,True
9456,Accounting Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,accounting manager,construction residential commercial office rea...,True
9571,Electro-Mechanical Procurement Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,electro mechanical procurement engineer,construction residential commercial office hos...,True
9643,Architect/ Interior Designer,['nan'],"['Architectural and Design Services', 'Constru...",NaN,architect interior designer,architectural design service construction resi...,True
9748,Technical Drive Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,technical drive engineer,construction residential commercial office,True
9864,Senior HVAC Engineer,['nan'],['Construction - Residential & Commercial/Offi...,NaN,senior hvac engineer,construction residential commercial office hos...,True
9895,Facade Surveyor,['nan'],['Construction - Residential & Commercial/Offi...,NaN,facade surveyor,construction residential commercial office con...,True
10104,Receivable Accountant,['nan'],"['Architectural and Design Services', 'Recreat...",NaN,receivable accountant,architectural design service recreational faci...,True
10174,Digital Marketing Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,digital marketing manager,construction residential commercial office rea...,True
10312,Sales Representative,['nan'],['Construction - Residential & Commercial/Offi...,NaN,sale representative,construction residential commercial office rea...,True
10381,Leasing Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,leasing manager,construction residential commercial office rea...,True
10521,Specialty Leasing Manager,['nan'],['Construction - Residential & Commercial/Offi...,NaN,specialty leasing manager,construction residential commercial office rea...,True
10558,Social Media Specialist - Mohandessin,['nan'],['Construction - Residential & Commercial/Offi...,NaN,social medium specialist mohandessin,construction residential commercial office rea...,True
10738,Sales Executive - B2B,['nan'],"['Engineering Services', 'Architectural and De...",NaN,sale executive b b,engineering service architectural design servi...,True
10774,General Accountant,['nan'],['Construction - Residential & Commercial/Offi...,NaN,general accountant,construction residential commercial office rea...,True

In [55]:
nullV = null_df['industryTXT'].values
dfV = df['industryTXT'].values
len(dfV)

10753

In [56]:
x= np.empty((10653,), dtype =str)
nullV1 = np.append(nullV,x)

In [57]:
dfV.shape == nullV1.shape

True

In [58]:
arrFlag = np.equal(dfV,nullV1)
arrFlag

array([False, False, False, ..., False, False, False])

In [59]:
df['flag'] = arrFlag

In [60]:
df

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,flag
0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising,False
1,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services'],installation maintenance repair software devel...,cisco collaboration specialist engineer,information technology service,False
2,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']",engineering telecom technology software develo...,senior back end php developer,computer software computer networking,False
3,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ...",creative design art software development,ux designer,computer software information technology servi...,False
4,Java Technical Lead,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Information Technology ...",engineering telecom technology software develo...,java technical lead,computer software information technology service,False
5,Technical Support Engineer,"['IT/Software Development', 'Engineering - Tel...","['Information Technology Services', 'Computer ...",software development engineering telecom techn...,technical support engineer,information technology service computer software,False
6,Senior iOS Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Graphic D...",engineering telecom technology software develo...,senior io developer,information technology service graphic design ...,False
7,Mechanical Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Enginee...",engineering mechanical electrical,mechanical engineer,architectural design service engineering servi...,False
8,Real Estate Sales Specialist - 10th of Ramadan,['Sales/Retail'],['Real Estate/Property Management'],sale retail,real estate sale specialist th ramadan,real estate property management,False
9,School Principal,"['Education/Teaching', 'Administration', 'Oper...",['Education'],education teaching administration operation ma...,school principal,education,False
10,Senior Sales Representative,"['Sales/Retail', 'Marketing/PR/Advertising', '...",['Marketing and Advertising'],sale retail marketing pr advertising medium jo...,senior sale representative,marketing advertising,False
11,Accountant,['Accounting/Finance'],['Education'],accounting finance,accountant,education,False
12,Indoor Sales Executive,"['Sales/Retail', 'Creative/Design/Art']","['Architectural and Design Services', 'Manufac...",sale retail creative design art,indoor sale executive,architectural design service manufacturing fur...,False
13,PHP Full-Stack - Joomla Expert,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services'],software development engineering telecom techn...,php full stack joomla expert,information technology service,False
14,English Teacher Assistant,['Education/Teaching'],['Education'],education teaching,english teacher assistant,education,False
15,Marketing Coordinator,"['Media/Journalism/Publishing', 'Marketing/PR/...",['Marketing and Advertising'],medium journalism publishing marketing pr adve...,marketing coordinator,marketing advertising,False
16,Senior Business Developer,"['Marketing/PR/Advertising', 'Sales/Retail']","['Marketing and Advertising', 'Computer Softwa...",marketing pr advertising sale retail,senior business developer,marketing advertising computer software public...,False
17,Senior Website Developer,"['IT/Software Development', 'Engineering - Tel...","['Insurance', 'Computer Software']",software development engineering telecom techn...,senior website developer,insurance computer software,False
18,Chief Accountant,['Accounting/Finance'],['Education'],accounting finance,chief accountant,education,False
19,Senior Front-End Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Information Technology Services', 'Internet/...",engineering telecom technology software develo...,senior front end developer,information technology service internet e comm...,False
20,Sales Account Manager - Google Cloud,"['IT/Software Development', 'Sales/Retail', 'E...","['Computer Software', 'Information Technology ...",software development sale retail engineering t...,sale account manager google cloud,computer software information technology service,False
21,Senior Back-End Developer,"['IT/Software Development', 'Engineering - Tel...",['Education'],software development engineering telecom techn...,senior back end developer,education,False
22,Video Editor,"['Creative/Design/Art', 'Media/Journalism/Publ...",['Marketing and Advertising'],creative design art medium journalism publishing,video editor,marketing advertising,False
23,Digital Marketing Specialist,['Marketing/PR/Advertising'],['Marketing and Advertising'],marketing pr advertising,digital marketing specialist,marketing advertising,False
24,Mechanical Technical Office Engineer,['Engineering - Mechanical/Electrical'],"['Architectural and Design Services', 'Constru...",engineering mechanical electrical,mechanical technical office engineer,architectural design service construction resi...,False
25,Sales Engineer,"['IT/Software Development', 'Sales/Retail']","['Information Technology Services', 'Consultin...",software development sale retail,sale engineer,information technology service consulting serv...,False
26,German Teacher - American School,['Education/Teaching'],['Education'],education teaching,german teacher american school,education,False
27,Personal Assistant,['Administration'],"['Real Estate/Property Management', 'Business ...",administration,personal assistant,real estate property management business suppl...,False
28,Sales Account Manager,['Sales/Retail'],"['Logistics and Supply Chain', 'Translation an...",sale retail,sale account manager,logistics supply chain translation localizatio...,False
29,Sales Coordinator/Telesales,"['Administration', 'Operations/Management', 'S...",['Information Technology Services'],administration operation management sale retail,sale coordinator telesales,information technology service,False
...,...,...,...,...,...,...,...
10840,Production Manager - PE Film Extrusion line,"['Manufacturing/Production', 'Engineering - Me...","['Manufacturing', 'Publishing and Printing', '...",manufacturing production engineering mechanica...,production manager pe film extrusion line,manufacturing publishing printing chemical,False
10841,Customer Support Engineer,"['Engineering - Telecom/Technology', 'Engineer...","['Computer Software', 'Information Technology ...",engineering telecom technology engineering mec...,customer support engineer,computer software information technology servi...,False
10842,Nursery Psychologist,['Education/Teaching'],['Education'],education teaching,nursery psychologist,education,False
10843,Managing Director - Kuwait,['Sales/Retail'],['Information Technology Services'],sale retail,managing director kuwait,information technology service,False
10844,Office Manager,"['Administration', 'Human Resources']",['Manufacturing'],administration human resource,office manager,manufacturing,False
10845,Senior Software Business Analyst,"['IT/Software Development', 'Analyst/Research'...",['Information Technology Services'],software development analyst research engineer...,senior software business analyst,information technology service,False
10846,Public Relations Manager,"['Marketing/PR/Advertising', 'Media/Journalism...","['Human Resources', 'Computer Software']",marketing pr advertising medium journalism pub...,public relation manager,human resource computer software,False
10847,Property Sales Consultant - Real Estate,['Sales/Retail'],['Real Estate/Property Management'],sale retail,property sale consultant real estate,real estate property management,False
10848,Real Estate Sales Agent,['Sales/Retail'],['Real Estate/Property Management'],sale retail,real estate sale agent,real estate property management,False
10849,Web Designer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...","['Internet/E-commerce', 'Information Technolog...",engineering telecom technology software develo...,web designer alexandria,internet e commerce information technology ser...,False
10850,Senior Marketing Executive,"['Marketing/PR/Advertising', 'Media/Journalism...","['Marketing and Advertising', 'Real Estate/Pro...",marketing pr advertising medium journalism pub...,senior marketing executive,marketing advertising real estate property man...,False
10851,Outdoor Sales Representative - Alexandria,"['Customer Service/Support', 'Sales/Retail']","['Graphic Design', 'Computer Software', 'Marke...",customer service support sale retail,outdoor sale representative alexandria,graphic design computer software marketing adv...,False
10852,Front-End Web Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Healthcare and Medical ...",engineering telecom technology software develo...,front end web developer,computer software healthcare medical service,False
10853,Sales Executive,['Sales/Retail'],"['Information Technology Services', 'Translati...",sale retail,sale executive,information technology service translation loc...,False
10854,Secretary,['Administration'],['Marketing and Advertising'],administration,secretary,marketing advertising,False
10855,QA Engineer,"['IT/Software Development', 'Quality']","['Engineering Services', 'Computer Software']",software development quality,qa engineer,engineering service computer software,False
10856,Senior .Net Web Developer,"['IT/Software Development', 'Engineering - Tel...",['Computer Software'],software development engineering telecom techn...,senior net web developer,computer software,False
10857,Property Advisor,['Sales/Retail'],['Real Estate/Property Management'],sale retail,property advisor,real estate property management,False
10858,Pharmacist,['Pharmaceutical'],"['Pharmaceuticals', 'Health, Wellness and Fitn...",pharmaceutical,pharmacist,pharmaceutical health wellness fitness healthc...,False
10859,Arabic KG Teacher - مُدرسة لغة عربية رياض أطفال,['Education/Teaching'],['Education'],education teaching,"arabic kg teacher Arabic teacher, kindergarten",education,False
10860,"Receptionist, Front Desk Clerk","['Medical/Healthcare', 'Hospitality/Hotels/Foo...","['Hospitality/Hotels', 'Healthcare and Medical...",medical healthcare hospitality hotel food service,receptionist front desk clerk,hospitality hotel healthcare medical service,False
10861,iOS Developer,"['IT/Software Development', 'Engineering - Tel...","['Computer Software', 'Information Technology ...",software development engineering telecom techn...,io developer,computer software information technology service,False
10862,Sales Executive,['Sales/Retail'],"['Marketing and Advertising', 'Furniture']",sale retail,sale executive,marketing advertising furniture,False
10863,Solution Developer / Back-End Developer Subjec...,"['Engineering - Telecom/Technology', 'IT/Softw...",['Computer Software'],engineering telecom technology software develo...,solution developer back end developer subject ...,computer software,False
10864,Marketing Specialist,"['Marketing/PR/Advertising', 'Media/Journalism...","['Marketing and Advertising', 'Public Relation...",marketing pr advertising medium journalism pub...,marketing specialist,marketing advertising public relation communic...,False
10865,Odoo Developer,"['IT/Software Development', 'Engineering - Tel...","['Real Estate/Property Management', 'Manufactu...",software development engineering telecom techn...,odoo developer,real estate property management manufacturing,False
10866,Senior PHP Developer - Alexandria,"['Engineering - Telecom/Technology', 'IT/Softw...",['Information Technology Services'],engineering telecom technology software develo...,senior php developer alexandria,information technology service,False
10867,Sales & Account Manager (Real Estate / Medical...,"['Business Development', 'Sales/Retail', 'Cust...","['Real Estate/Property Management', 'Retail', ...",business development sale retail customer serv...,sale account manager real estate medical assiut,real estate property management retail healthc...,False
10868,Technical and Network Support Engineer - Alexa...,"['Installation/Maintenance/Repair', 'Engineeri...","['Computer Software', 'Education', 'Healthcare...",installation maintenance repair engineering te...,technical network support engineer alexandria,computer software education healthcare medical...,False
10869,Senior Java Developer,"['IT/Software Development', 'Engineering - Tel...",['Information Technology Services'],software development engineering telecom techn...,senior java developer,information technology service,False

In [61]:
df['flag'].value_counts()

False    10753
Name: flag, dtype: int64

In [62]:
s = [] 
'''
s= 
[index_JopFunction_Has_NaN'e.g:which title value = "x" ',
index_JopFunction_Dont_Has_NaN'e.g:which title value = "x" ']
'''
for inxi ,i in enumerate(dfV):
    for inxj,j in enumerate(nullV):
        if i == j:
            s.append([inxj,inxi])

In [63]:
len(s)

4665

In [64]:
s = sorted(s)
s

[[0, 34],
 [0, 485],
 [0, 513],
 [0, 609],
 [0, 756],
 [0, 955],
 [0, 1086],
 [0, 1090],
 [0, 1200],
 [0, 1280],
 [0, 1337],
 [0, 1387],
 [0, 1390],
 [0, 1424],
 [0, 1427],
 [0, 1494],
 [0, 1714],
 [0, 1739],
 [0, 1882],
 [0, 4227],
 [0, 4394],
 [0, 4464],
 [0, 4936],
 [0, 5344],
 [0, 5458],
 [0, 5472],
 [0, 5542],
 [0, 5642],
 [0, 5680],
 [0, 6892],
 [0, 7249],
 [0, 8188],
 [0, 9226],
 [1, 5367],
 [2, 34],
 [2, 485],
 [2, 513],
 [2, 609],
 [2, 756],
 [2, 955],
 [2, 1086],
 [2, 1090],
 [2, 1200],
 [2, 1280],
 [2, 1337],
 [2, 1387],
 [2, 1390],
 [2, 1424],
 [2, 1427],
 [2, 1494],
 [2, 1714],
 [2, 1739],
 [2, 1882],
 [2, 4227],
 [2, 4394],
 [2, 4464],
 [2, 4936],
 [2, 5344],
 [2, 5458],
 [2, 5472],
 [2, 5542],
 [2, 5642],
 [2, 5680],
 [2, 6892],
 [2, 7249],
 [2, 8188],
 [2, 9226],
 [3, 34],
 [3, 485],
 [3, 513],
 [3, 609],
 [3, 756],
 [3, 955],
 [3, 1086],
 [3, 1090],
 [3, 1200],
 [3, 1280],
 [3, 1337],
 [3, 1387],
 [3, 1390],
 [3, 1424],
 [3, 1427],
 [3, 1494],
 [3, 1714],
 [3, 1739],
 [3, 1882],
 [3, 4227],
 [3, 4394],
 [3, 4464],
 [3, 4936],
 [3, 5344],
 [3, 5458],
 [3, 5472],
 [3, 5542],
 [3, 5642],
 [3, 5680],
 [3, 6892],
 [3, 7249],
 [3, 8188],
 [3, 9226],
 [4, 34],
 [4, 485],
 [4, 513],
 [4, 609],
 [4, 756],
 [4, 955],
 [4, 1086],
 [4, 1090],
 [4, 1200],
 [4, 1280],
 [4, 1337],
 [4, 1387],
 [4, 1390],
 [4, 1424],
 [4, 1427],
 [4, 1494],
 [4, 1714],
 [4, 1739],
 [4, 1882],
 [4, 4227],
 [4, 4394],
 [4, 4464],
 [4, 4936],
 [4, 5344],
 [4, 5458],
 [4, 5472],
 [4, 5542],
 [4, 5642],
 [4, 5680],
 [4, 6892],
 [4, 7249],
 [4, 8188],
 [4, 9226],
 [5, 824],
 [5, 1297],
 [5, 1515],
 [5, 2332],
 [5, 2525],
 [5, 2917],
 [5, 3940],
 [5, 4120],
 [5, 4699],
 [5, 4776],
 [5, 4857],
 [5, 6370],
 [5, 6523],
 [5, 7101],
 [5, 7247],
 [5, 7549],
 [5, 8384],
 [6, 58],
 [6, 131],
 [6, 201],
 [6, 214],
 [6, 271],
 [6, 344],
 [6, 439],
 [6, 586],
 [6, 628],
 [6, 779],
 [6, 896],
 [6, 969],
 [6, 1032],
 [6, 1077],
 [6, 1165],
 [6, 1344],
 [6, 1708],
 [6, 1736],
 [6, 1934],
 [6, 2115],
 [6, 2410],
 [6, 2681],
 [6, 2776],
 [6, 2859],
 [6, 2934],
 [6, 3018],
 [6, 3075],
 [6, 3082],
 [6, 3152],
 [6, 3232],
 [6, 3464],
 [6, 3532],
 [6, 3588],
 [6, 3619],
 [6, 3809],
 [6, 3824],
 [6, 3999],
 [6, 4013],
 [6, 4031],
 [6, 4212],
 [6, 4265],
 [6, 4309],
 [6, 4399],
 [6, 4472],
 [6, 4484],
 [6, 4503],
 [6, 4561],
 [6, 4630],
 [6, 4635],
 [6, 4680],
 [6, 4888],
 [6, 4967],
 [6, 5004],
 [6, 5076],
 [6, 5152],
 [6, 5181],
 [6, 5208],
 [6, 5230],
 [6, 5302],
 [6, 5385],
 [6, 5391],
 [6, 5491],
 [6, 5496],
 [6, 5534],
 [6, 5613],
 [6, 5624],
 [6, 5681],
 [6, 5720],
 [6, 5758],
 [6, 5856],
 [6, 5909],
 [6, 5949],
 [6, 5985],
 [6, 6034],
 [6, 6064],
 [6, 6101],
 [6, 6179],
 [6, 6183],
 [6, 6258],
 [6, 6331],
 [6, 6357],
 [6, 6411],
 [6, 6444],
 [6, 6485],
 [6, 6557],
 [6, 6607],
 [6, 6641],
 [6, 6759],
 [6, 6786],
 [6, 6952],
 [6, 7100],
 [6, 7115],
 [6, 7578],
 [6, 7619],
 [6, 7755],
 [6, 8186],
 [6, 8861],
 [6, 8894],
 [6, 9175],
 [6, 9909],
 [6, 10046],
 [6, 10608],
 [6, 10679],
 [7, 58],
 [7, 131],
 [7, 201],
 [7, 214],
 [7, 271],
 [7, 344],
 [7, 439],
 [7, 586],
 [7, 628],
 [7, 779],
 [7, 896],
 [7, 969],
 [7, 1032],
 [7, 1077],
 [7, 1165],
 [7, 1344],
 [7, 1708],
 [7, 1736],
 [7, 1934],
 [7, 2115],
 [7, 2410],
 [7, 2681],
 [7, 2776],
 [7, 2859],
 [7, 2934],
 [7, 3018],
 [7, 3075],
 [7, 3082],
 [7, 3152],
 [7, 3232],
 [7, 3464],
 [7, 3532],
 [7, 3588],
 [7, 3619],
 [7, 3809],
 [7, 3824],
 [7, 3999],
 [7, 4013],
 [7, 4031],
 [7, 4212],
 [7, 4265],
 [7, 4309],
 [7, 4399],
 [7, 4472],
 [7, 4484],
 [7, 4503],
 [7, 4561],
 [7, 4630],
 [7, 4635],
 [7, 4680],
 [7, 4888],
 [7, 4967],
 [7, 5004],
 [7, 5076],
 [7, 5152],
 [7, 5181],
 [7, 5208],
 [7, 5230],
 [7, 5302],
 [7, 5385],
 [7, 5391],
 [7, 5491],
 [7, 5496],
 [7, 5534],
 [7, 5613],
 [7, 5624],
 [7, 5681],
 [7, 5720],
 [7, 5758],
 [7, 5856],
 [7, 5909],
 [7, 5949],
 [7, 5985],
 [7, 6034],
 [7, 6064],
 [7, 6101],
 [7, 6179],
 [7, 6183],
 [7, 6258],
 [7, 6331],
 [7, 6357],
 [7, 6411],
 [7, 6444],
 [7, 6485],
 [7, 6557],
 [7, 6607],
 [7, 6641],
 [7, 6759],
 [7, 6786],
 [7, 6952],
 [7, 7100],
 [7, 7115],
 [7, 7578],
 [7, 7619],
 [7, 7755],
 [7, 8186],
 [7, 8861],
 [7, 8894],
 [7, 9175],
 [7, 9909],
 [7, 10046],
 [7, 10608],
 [7, 10679],
 [8, 824],
 [8, 1297],
 [8, 1515],
 [8, 2332],
 [8, 2525],
 [8, 2917],
 [8, 3940],
 [8, 4120],
 [8, 4699],
 [8, 4776],
 [8, 4857],
 [8, 6370],
 [8, 6523],
 [8, 7101],
 [8, 7247],
 [8, 7549],
 [8, 8384],
 [9, 58],
 [9, 131],
 [9, 201],
 [9, 214],
 [9, 271],
 [9, 344],
 [9, 439],
 [9, 586],
 [9, 628],
 [9, 779],
 [9, 896],
 [9, 969],
 [9, 1032],
 [9, 1077],
 [9, 1165],
 [9, 1344],
 [9, 1708],
 [9, 1736],
 [9, 1934],
 [9, 2115],
 [9, 2410],
 [9, 2681],
 [9, 2776],
 [9, 2859],
 [9, 2934],
 [9, 3018],
 [9, 3075],
 [9, 3082],
 [9, 3152],
 [9, 3232],
 [9, 3464],
 [9, 3532],
 [9, 3588],
 [9, 3619],
 [9, 3809],
 [9, 3824],
 [9, 3999],
 [9, 4013],
 [9, 4031],
 [9, 4212],
 [9, 4265],
 [9, 4309],
 [9, 4399],
 [9, 4472],
 [9, 4484],
 [9, 4503],
 [9, 4561],
 [9, 4630],
 [9, 4635],
 [9, 4680],
 [9, 4888],
 [9, 4967],
 [9, 5004],
 [9, 5076],
 [9, 5152],
 [9, 5181],
 [9, 5208],
 [9, 5230],
 [9, 5302],
 [9, 5385],
 [9, 5391],
 [9, 5491],
 [9, 5496],
 [9, 5534],
 [9, 5613],
 [9, 5624],
 [9, 5681],
 [9, 5720],
 [9, 5758],
 [9, 5856],
 [9, 5909],
 [9, 5949],
 [9, 5985],
 [9, 6034],
 [9, 6064],
 [9, 6101],
 [9, 6179],
 [9, 6183],
 [9, 6258],
 [9, 6331],
 [9, 6357],
 [9, 6411],
 [9, 6444],
 [9, 6485],
 [9, 6557],
 [9, 6607],
 [9, 6641],
 [9, 6759],
 [9, 6786],
 [9, 6952],
 [9, 7100],
 [9, 7115],
 [9, 7578],
 [9, 7619],
 [9, 7755],
 [9, 8186],
 [9, 8861],
 [9, 8894],
 [9, 9175],
 [9, 9909],
 [9, 10046],
 [9, 10608],
 [9, 10679],
 [10, 58],
 [10, 131],
 [10, 201],
 [10, 214],
 [10, 271],
 [10, 344],
 [10, 439],
 [10, 586],
 [10, 628],
 [10, 779],
 [10, 896],
 [10, 969],
 [10, 1032],
 [10, 1077],
 [10, 1165],
 [10, 1344],
 [10, 1708],
 [10, 1736],
 [10, 1934],
 [10, 2115],
 [10, 2410],
 [10, 2681],
 [10, 2776],
 [10, 2859],
 [10, 2934],
 [10, 3018],
 [10, 3075],
 [10, 3082],
 [10, 3152],
 [10, 3232],
 [10, 3464],
 [10, 3532],
 [10, 3588],
 [10, 3619],
 [10, 3809],
 [10, 3824],
 [10, 3999],
 [10, 4013],
 [10, 4031],
 [10, 4212],
 [10, 4265],
 [10, 4309],
 [10, 4399],
 [10, 4472],
 [10, 4484],
 [10, 4503],
 [10, 4561],
 [10, 4630],
 [10, 4635],
 [10, 4680],
 [10, 4888],
 [10, 4967],
 [10, 5004],
 [10, 5076],
 [10, 5152],
 [10, 5181],
 [10, 5208],
 [10, 5230],
 [10, 5302],
 [10, 5385],
 [10, 5391],
 [10, 5491],
 [10, 5496],
 [10, 5534],
 [10, 5613],
 [10, 5624],
 [10, 5681],
 [10, 5720],
 [10, 5758],
 [10, 5856],
 [10, 5909],
 [10, 5949],
 [10, 5985],
 [10, 6034],
 [10, 6064],
 [10, 6101],
 [10, 6179],
 [10, 6183],
 [10, 6258],
 [10, 6331],
 [10, 6357],
 [10, 6411],
 [10, 6444],
 [10, 6485],
 [10, 6557],
 [10, 6607],
 [10, 6641],
 [10, 6759],
 [10, 6786],
 [10, 6952],
 [10, 7100],
 [10, 7115],
 [10, 7578],
 [10, 7619],
 [10, 7755],
 [10, 8186],
 [10, 8861],
 [10, 8894],
 [10, 9175],
 [10, 9909],
 [10, 10046],
 [10, 10608],
 [10, 10679],
 [11, 58],
 [11, 131],
 [11, 201],
 [11, 214],
 [11, 271],
 [11, 344],
 [11, 439],
 [11, 586],
 [11, 628],
 [11, 779],
 [11, 896],
 [11, 969],
 [11, 1032],
 [11, 1077],
 [11, 1165],
 [11, 1344],
 [11, 1708],
 [11, 1736],
 [11, 1934],
 [11, 2115],
 [11, 2410],
 [11, 2681],
 [11, 2776],
 [11, 2859],
 [11, 2934],
 [11, 3018],
 [11, 3075],
 [11, 3082],
 [11, 3152],
 [11, 3232],
 [11, 3464],
 [11, 3532],
 [11, 3588],
 [11, 3619],
 [11, 3809],
 [11, 3824],
 [11, 3999],
 [11, 4013],
 [11, 4031],
 [11, 4212],
 [11, 4265],
 [11, 4309],
 [11, 4399],
 [11, 4472],
 [11, 4484],
 [11, 4503],
 [11, 4561],
 [11, 4630],
 [11, 4635],
 [11, 4680],
 [11, 4888],
 [11, 4967],
 [11, 5004],
 [11, 5076],
 [11, 5152],
 [11, 5181],
 [11, 5208],
 [11, 5230],
 [11, 5302],
 [11, 5385],
 [11, 5391],
 [11, 5491],
 [11, 5496],
 [11, 5534],
 [11, 5613],
 [11, 5624],
 [11, 5681],
 [11, 5720],
 [11, 5758],
 [11, 5856],
 [11, 5909],
 [11, 5949],
 [11, 5985],
 [11, 6034],
 [11, 6064],
 [11, 6101],
 [11, 6179],
 [11, 6183],
 [11, 6258],
 [11, 6331],
 [11, 6357],
 [11, 6411],
 [11, 6444],
 [11, 6485],
 [11, 6557],
 [11, 6607],
 [11, 6641],
 [11, 6759],
 [11, 6786],
 [11, 6952],
 [11, 7100],
 [11, 7115],
 [11, 7578],
 [11, 7619],
 [11, 7755],
 [11, 8186],
 [11, 8861],
 [11, 8894],
 [11, 9175],
 [11, 9909],
 [11, 10046],
 [11, 10608],
 [11, 10679],
 [12, 34],
 [12, 485],
 [12, 513],
 [12, 609],
 [12, 756],
 [12, 955],
 [12, 1086],
 [12, 1090],
 [12, 1200],
 [12, 1280],
 [12, 1337],
 [12, 1387],
 [12, 1390],
 [12, 1424],
 [12, 1427],
 [12, 1494],
 [12, 1714],
 [12, 1739],
 [12, 1882],
 [12, 4227],
 [12, 4394],
 [12, 4464],
 [12, 4936],
 [12, 5344],
 [12, 5458],
 [12, 5472],
 [12, 5542],
 [12, 5642],
 [12, 5680],
 [12, 6892],
 [12, 7249],
 [12, 8188],
 [12, 9226],
 [13, 464],
 [14, 34],
 [14, 485],
 [14, 513],
 [14, 609],
 [14, 756],
 [14, 955],
 [14, 1086],
 [14, 1090],
 [14, 1200],
 [14, 1280],
 [14, 1337],
 [14, 1387],
 [14, 1390],
 [14, 1424],
 [14, 1427],
 [14, 1494],
 [14, 1714],
 [14, 1739],
 [14, 1882],
 [14, 4227],
 [14, 4394],
 [14, 4464],
 [14, 4936],
 [14, 5344],
 [14, 5458],
 [14, 5472],
 [14, 5542],
 [14, 5642],
 [14, 5680],
 [14, 6892],
 [14, 7249],
 [14, 8188],
 [14, 9226],
 [15, 34],
 [15, 485],
 [15, 513],
 [15, 609],
 [15, 756],
 [15, 955],
 [15, 1086],
 [15, 1090],
 [15, 1200],
 [15, 1280],
 [15, 1337],
 [15, 1387],
 [15, 1390],
 [15, 1424],
 [15, 1427],
 [15, 1494],
 [15, 1714],
 [15, 1739],
 [15, 1882],
 [15, 4227],
 [15, 4394],
 [15, 4464],
 [15, 4936],
 [15, 5344],
 [15, 5458],
 [15, 5472],
 [15, 5542],
 [15, 5642],
 [15, 5680],
 [15, 6892],
 [15, 7249],
 [15, 8188],
 [15, 9226],
 [16, 58],
 [16, 131],
 [16, 201],
 [16, 214],
 [16, 271],
 [16, 344],
 [16, 439],
 [16, 586],
 [16, 628],
 [16, 779],
 [16, 896],
 [16, 969],
 [16, 1032],
 [16, 1077],
 [16, 1165],
 [16, 1344],
 [16, 1708],
 [16, 1736],
 [16, 1934],
 [16, 2115],
 [16, 2410],
 [16, 2681],
 [16, 2776],
 [16, 2859],
 [16, 2934],
 [16, 3018],
 [16, 3075],
 [16, 3082],
 [16, 3152],
 [16, 3232],
 [16, 3464],
 [16, 3532],
 [16, 3588],
 [16, 3619],
 [16, 3809],
 [16, 3824],
 [16, 3999],
 [16, 4013],
 [16, 4031],
 [16, 4212],
 [16, 4265],
 [16, 4309],
 [16, 4399],
 [16, 4472],
 [16, 4484],
 [16, 4503],
 [16, 4561],
 [16, 4630],
 [16, 4635],
 [16, 4680],
 [16, 4888],
 [16, 4967],
 [16, 5004],
 [16, 5076],
 [16, 5152],
 [16, 5181],
 [16, 5208],
 [16, 5230],
 [16, 5302],
 [16, 5385],
 [16, 5391],
 [16, 5491],
 [16, 5496],
 [16, 5534],
 [16, 5613],
 [16, 5624],
 [16, 5681],
 [16, 5720],
 [16, 5758],
 [16, 5856],
 [16, 5909],
 [16, 5949],
 [16, 5985],
 [16, 6034],
 [16, 6064],
 [16, 6101],
 [16, 6179],
 [16, 6183],
 [16, 6258],
 [16, 6331],
 [16, 6357],
 [16, 6411],
 [16, 6444],
 [16, 6485],
 [16, 6557],
 [16, 6607],
 [16, 6641],
 [16, 6759],
 [16, 6786],
 [16, 6952],
 [16, 7100],
 [16, 7115],
 [16, 7578],
 [16, 7619],
 [16, 7755],
 [16, 8186],
 [16, 8861],
 [16, 8894],
 [16, 9175],
 [16, 9909],
 [16, 10046],
 [16, 10608],
 [16, 10679],
 [17, 58],
 [17, 131],
 [17, 201],
 [17, 214],
 [17, 271],
 [17, 344],
 [17, 439],
 [17, 586],
 [17, 628],
 [17, 779],
 [17, 896],
 [17, 969],
 [17, 1032],
 [17, 1077],
 [17, 1165],
 [17, 1344],
 [17, 1708],
 [17, 1736],
 [17, 1934],
 [17, 2115],
 [17, 2410],
 [17, 2681],
 [17, 2776],
 [17, 2859],
 [17, 2934],
 [17, 3018],
 [17, 3075],
 [17, 3082],
 [17, 3152],
 [17, 3232],
 [17, 3464],
 [17, 3532],
 [17, 3588],
 [17, 3619],
 [17, 3809],
 [17, 3824],
 [17, 3999],
 [17, 4013],
 [17, 4031],
 [17, 4212],
 [17, 4265],
 [17, 4309],
 [17, 4399],
 [17, 4472],
 [17, 4484],
 [17, 4503],
 [17, 4561],
 [17, 4630],
 [17, 4635],
 [17, 4680],
 [17, 4888],
 [17, 4967],
 [17, 5004],
 [17, 5076],
 [17, 5152],
 [17, 5181],
 [17, 5208],
 [17, 5230],
 [17, 5302],
 [17, 5385],
 [17, 5391],
 [17, 5491],
 [17, 5496],
 [17, 5534],
 [17, 5613],
 [17, 5624],
 [17, 5681],
 [17, 5720],
 [17, 5758],
 [17, 5856],
 [17, 5909],
 [17, 5949],
 [17, 5985],
 [17, 6034],
 [17, 6064],
 [17, 6101],
 [17, 6179],
 [17, 6183],
 [17, 6258],
 [17, 6331],
 [17, 6357],
 [17, 6411],
 [17, 6444],
 [17, 6485],
 [17, 6557],
 [17, 6607],
 [17, 6641],
 [17, 6759],
 [17, 6786],
 [17, 6952],
 [17, 7100],
 [17, 7115],
 [17, 7578],
 [17, 7619],
 [17, 7755],
 [17, 8186],
 [17, 8861],
 [17, 8894],
 [17, 9175],
 [17, 9909],
 [17, 10046],
 [17, 10608],
 [17, 10679],
 [18, 34],
 [18, 485],
 [18, 513],
 [18, 609],
 [18, 756],
 [18, 955],
 [18, 1086],
 [18, 1090],
 [18, 1200],
 [18, 1280],
 [18, 1337],
 [18, 1387],
 ...]

In [65]:
flag = []
for i in s:
    if i[0] not in flag:
        flag.append(i[0])
        continue
    s.remove(i)

In [66]:
for i in s:
    null_df['jobFunctionTxt'].iloc[i[0]] = df['jobFunctionTxt'].iloc[i[1]]

C:\Users\elnafad\Anaconda4\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [67]:
null_df['jobFunctionTxt'].iloc[0]

'administration'

In [68]:
null_df['jobFunctionTxt'].iloc[0] == df['jobFunctionTxt'].iloc[34]

False

In [69]:
null_df

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,eq
69,Finishing Foreman,['nan'],['Construction - Residential & Commercial/Offi...,administration,finishing foreman,construction residential commercial office rea...,True
148,Site Accountant,['nan'],"['Engineering Services', 'Construction - Resid...",sale retail engineering construction civil arc...,site accountant,engineering service construction residential c...,True
378,Chief Accountant,['nan'],['Construction - Residential & Commercial/Offi...,administration,chief accountant,construction residential commercial office rea...,True
517,Sales Representative - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,administration,sale representative real estate,construction residential commercial office rea...,True
651,BMS Projects Electrical Engineer/ Alexandria,['nan'],['Construction - Residential & Commercial/Offi...,administration,bm project electrical engineer alexandria,construction residential commercial office rea...,True
718,Technical Office Engineer/ Civil,['nan'],['Construction - Residential & Commercial/Offi...,accounting finance,technical office engineer civil,construction residential commercial office con...,True
894,Sales Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,sale manager,construction residential commercial office,True
1001,Structural Engineer - Combustion Equipment & B...,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,structural engineer combustion equipment boile...,construction residential commercial office,True
1116,Purchasing Specialist,['nan'],['Construction - Residential & Commercial/Offi...,accounting finance,purchasing specialist,construction residential commercial office con...,True
1187,Real Estate Marketing Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,real estate marketing manager,construction residential commercial office,True
1411,Senior Technical Office Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,senior technical office mechanical engineer,construction residential commercial office,True
1485,Site Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,site manager,construction residential commercial office,True
1599,Graphic Designer,['nan'],['Construction - Residential & Commercial/Offi...,administration,graphic designer,construction residential commercial office rea...,True
1675,Food Plant Manager,['nan'],"['Architectural and Design Services', 'Constru...",operation management purchasing procurement,food plant manager,architectural design service construction indu...,True
1831,Senior Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration,senior site engineer,construction residential commercial office rea...,True
1872,Senior Sanitary Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration,senior sanitary engineer,construction residential commercial office rea...,True
2019,Site Engineer - Architecture / Civil Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,site engineer architecture civil engineer,construction residential commercial office,True
2098,Technical Office Team Leader,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,technical office team leader,construction residential commercial office,True
2214,Senior General Accountant,['nan'],['Construction - Residential & Commercial/Offi...,administration,senior general accountant,construction residential commercial office rea...,True
2253,Store Supervisor,['nan'],['Construction - Residential & Commercial/Offi...,business development sale retail customer serv...,store supervisor,construction residential commercial office int...,True
2411,Purchasing Specialist,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,purchasing specialist,construction residential commercial office,True
2483,Site Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,site engineer,construction residential commercial office,True
2592,Constructional Engineer,['nan'],"['Architectural and Design Services', 'Constru...",installation maintenance repair customer servi...,constructional engineer,architectural design service construction resi...,True
2631,Project Manager,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,project manager,construction residential commercial office,True
2860,Contact Center Agent,['nan'],['Construction - Residential & Commercial/Offi...,purchasing procurement engineering constructio...,contact center agent,construction residential commercial office rea...,True
2976,Marketing Specialist - Curtains,['nan'],['Construction - Residential & Commercial/Offi...,engineering mechanical electrical operation ma...,marketing specialist curtain,construction residential commercial office con...,True
3092,Electrical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,electrical engineer,construction residential commercial office,True
3248,Document Control,['nan'],"['Architectural and Design Services', 'Constru...",project program management engineering constru...,document control,architectural design service construction resi...,True
3322,Executive Architectural Project Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,executive architectural project manager,construction residential commercial office,True
3397,Architecture Technical Office Engineer on Site,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,architecture technical office engineer site,construction residential commercial office,True
...,...,...,...,...,...,...,...
7923,Agriculture Engineer - Real Estate,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,agriculture engineer real estate,construction residential commercial office,True
7992,Projects Sales Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,project sale engineer,construction residential commercial office,True
8167,Warehouse Manager,['nan'],['Construction - Residential & Commercial/Offi...,engineering mechanical electrical,warehouse manager,construction residential commercial office con...,True
8282,Quality Control Specialist - Chemist,['nan'],['Construction - Residential & Commercial/Offi...,sale retail,quality control specialist chemist,construction residential commercial office man...,True
8354,Finance Manager,['nan'],['Construction - Residential & Commercial/Offi...,customer service support,finance manager,construction residential commercial office ret...,True
8503,Site Finishing Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,site finishing engineer,construction residential commercial office,True
8614,Site Engineer,['nan'],"['Engineering Services', 'Architectural and De...",engineering mechanical electrical,site engineer,engineering service architectural design servi...,True
8654,Technical Office Finishing Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,technical office finishing engineer,construction residential commercial office,True
8755,Technical Office Engineer - Electrical,['nan'],['Construction - Residential & Commercial/Offi...,engineering mechanical electrical,technical office engineer electrical,construction residential commercial office con...,True
8828,Electrical Technical Office Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering mechanical electrical,electrical technical office engineer,construction residential commercial office con...,True
8939,Technical Office Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,technical office mechanical engineer,construction residential commercial office,True
9049,Site Mechanical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,site mechanical engineer,construction residential commercial office,True
9123,Site Electrical Engineer,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,site electrical engineer,construction residential commercial office,True
9198,Warehouse Operative,['nan'],['Construction - Residential & Commercial/Offi...,engineering mechanical electrical,warehouse operative,construction residential commercial office con...,True
9274,Accounting Manager,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,accounting manager,construction residential commercial office,True
9386,Site Civil Engineer - Industrial Mega Projects,['nan'],['Construction - Residential & Commercial/Offi...,engineering construction civil architecture ad...,site civil engineer industrial mega project,construction residential commercial office,True
9456,Accounting Manager,['nan'],['Construction - Residential & Commercial/Offi...,purchasing procurement engineering constructio...,accounting manager,construction residential commercial office rea...,True
9571,Electro-Mechanical Procurement Engineer,['nan'],['Construction - Residential & Commercial/Offi...,accounting finance,electro mechanical procurement engineer,construction residential commercial office hos...,True
9643,Architect/ Interior Designer,['nan'],"['Architectural and Design Services', 'Constru...",project program management engineering constru...,architect interior designer,architectural design service construction resi...,True
9748,Technical Drive Engineer,['nan'],['Construction - Residential & Commercial/Offi...,administration legal,technical drive engineer,construction residential commercial office,True
9864,Senior HVAC Engineer,['nan'],['Construction - Residential & Commercial/Offi...,accounting finance,senior hvac engineer,construction residential commercial office hos...,True
9895,Facade Surveyor,['nan'],['Construction - Residential & Commercial/Offi...,accounting finance,facade surveyor,construction residential commercial office con...,True
10104,Receivable Accountant,['nan'],"['Architectural and Design Services', 'Recreat...",human resource,receivable accountant,architectural design service recreational faci...,True
10174,Digital Marketing Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration,digital marketing manager,construction residential commercial office rea...,True
10312,Sales Representative,['nan'],['Construction - Residential & Commercial/Offi...,administration,sale representative,construction residential commercial office rea...,True
10381,Leasing Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration,leasing manager,construction residential commercial office rea...,True
10521,Specialty Leasing Manager,['nan'],['Construction - Residential & Commercial/Offi...,administration,specialty leasing manager,construction residential commercial office rea...,True
10558,Social Media Specialist - Mohandessin,['nan'],['Construction - Residential & Commercial/Offi...,administration,social medium specialist mohandessin,construction residential commercial office rea...,True
10738,Sales Executive - B2B,['nan'],"['Engineering Services', 'Architectural and De...",engineering mechanical electrical,sale executive b b,engineering service architectural design servi...,True
10774,General Accountant,['nan'],['Construction - Residential & Commercial/Offi...,purchasing procurement engineering constructio...,general accountant,construction residential commercial office rea...,True

In [70]:
df.iloc[34]

title                                Accounts Receivable Accountant
jobFunction                                  ['Accounting/Finance']
industry          ['Construction - Residential & Commercial/Offi...
jobFunctionTxt                                   accounting finance
titleTxt                              account receivable accountant
industryTXT       construction residential commercial office rea...
flag                                                          False
Name: 34, dtype: object

In [71]:
null_df.iloc[98]

title                                         Sales Executive - B2B
jobFunction                                                 ['nan']
industry          ['Engineering Services', 'Architectural and De...
jobFunctionTxt                    engineering mechanical electrical
titleTxt                                         sale executive b b
industryTXT       engineering service architectural design servi...
eq                                                             True
Name: 10738, dtype: object

In [72]:
df.iloc[2966]

title                                    Sales Executive - B2B
jobFunction       ['Sales/Retail', 'Customer Service/Support']
industry                     ['Education', 'Media Production']
jobFunctionTxt            sale retail customer service support
titleTxt                                    sale executive b b
industryTXT                        education medium production
flag                                                     False
Name: 2997, dtype: object

In [73]:
null_df.drop('eq' ,axis = 1 ,inplace = True)
#null_df.drop('eq' ,axis = 1 ,inplace = True)

In [74]:
mergedStuff = pd.merge(df, null_df, how='outer')

In [75]:
mergedStuff.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10853 entries, 0 to 10852
Data columns (total 7 columns):
title             10853 non-null object
jobFunction       10853 non-null object
industry          10853 non-null object
jobFunctionTxt    10853 non-null object
titleTxt          10853 non-null object
industryTXT       10853 non-null object
flag              10753 non-null object
dtypes: object(7)
memory usage: 678.3+ KB

In [76]:
df = mergedStuff
df.head()

,title,jobFunction,industry,jobFunctionTxt,titleTxt,industryTXT,flag
0,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising,False
1,Full Stack PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Marketing and Advertisi...",engineering telecom technology software develo...,full stack php developer,computer software marketing advertising,False
2,CISCO Collaboration Specialist Engineer,"['Installation/Maintenance/Repair', 'IT/Softwa...",['Information Technology Services'],installation maintenance repair software devel...,cisco collaboration specialist engineer,information technology service,False
3,Senior Back End-PHP Developer,"['Engineering - Telecom/Technology', 'IT/Softw...","['Computer Software', 'Computer Networking']",engineering telecom technology software develo...,senior back end php developer,computer software computer networking,False
4,UX Designer,"['Creative/Design/Art', 'IT/Software Developme...","['Computer Software', 'Information Technology ...",creative design art software development,ux designer,computer software information technology servi...,False

In [77]:
df.drop('flag' ,axis = 1 ,inplace = True)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10853 entries, 0 to 10852
Data columns (total 6 columns):
title             10853 non-null object
jobFunction       10853 non-null object
industry          10853 non-null object
jobFunctionTxt    10853 non-null object
titleTxt          10853 non-null object
industryTXT       10853 non-null object
dtypes: object(6)
memory usage: 593.5+ KB

### Feature Extraction by TF-IDF

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
#tf = TfidfVectorizer(analyzmer='word', ngram_range=(1, 3), min_df=0, stop_words='english')
allData = pd.DataFrame()
allData['dfTXT'] =  df['industryTXT']+df['jobFunctionTxt']+df['titleTxt']
tfidf_matrix = tfidf_vectorizer.fit_transform((allData['dfTXT']))
#tfidf_vectorizer.fit_transform((Merge_data['text']))

### Calculating Cosine Similarity

In [80]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import linear_kernel

cosine_similarities = linear_kernel(tfidf_matrix)
results = {}
for idx, row in df.iterrows():
    similar_indices = cosine_similarities[idx].argsort()[:-100:-1]
    similar_items = [(cosine_similarities[idx][i], df['titleTxt'][i]) for i in similar_indices]
    results[row['titleTxt']] = similar_items[1:]
    
print('done!')

done!

### Recommender System

In [81]:
def item(word):
    try:
        return df.loc[df['titleTxt'] == word]['jobFunctionTxt'].tolist()[0]
    except:
        print('sorry My Model dont Know U...OUT! '.upper())
# Just reads the results out of the dictionary.
def recommend(word, num):
    try:
        recs = results[word][:num]
        re = []
        g= 1
        for rec in recs:
            re.append("Recommended " +str(g)+':'+ item(rec[1]))
            re.append (" ( score = " + str(rec[0]) + " )")
            g=g+1
        return re
    except:
        print('sorry My Model dont Know U...OUT! '.upper())

### Test

In [82]:
r = recommend("full stack php developer",10)

In [83]:
r

['Recommended 1:software development engineering telecom technology',
 ' ( score = 0.8736424777626997 )',
 'Recommended 2:engineering telecom technology software development',
 ' ( score = 0.7672253040836755 )',
 'Recommended 3:engineering telecom technology software development',
 ' ( score = 0.7672253040836755 )',
 'Recommended 4:software development engineering telecom technology',
 ' ( score = 0.6505663416731007 )',
 'Recommended 5:software development engineering telecom technology',
 ' ( score = 0.646888757110688 )',
 'Recommended 6:software development engineering telecom technology',
 ' ( score = 0.646888757110688 )',
 'Recommended 7:software development engineering telecom technology',
 ' ( score = 0.646888757110688 )',
 'Recommended 8:software development engineering telecom technology',
 ' ( score = 0.646888757110688 )',
 'Recommended 9:software development engineering telecom technology',
 ' ( score = 0.646888757110688 )',
 'Recommended 10:software development engineering telecom technology',
 ' ( score = 0.6164145688362627 )']

# API

In [ ]:
from sys import platform
import pandas as pd
from flask import Flask,jsonify ,request
app = Flask(__name__)
@app.route('/job/<string:title>/<int:num>', methods=['GET'])
def test(title,num):
    lst = recommend(title,num)
    d = {lst[i]: lst[i + 1] for i in range(0, len(lst), 2)}  
    return jsonify(d)

app.run(debug=False)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [12/Jan/2020 04:16:06] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [12/Jan/2020 04:16:06] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [12/Jan/2020 04:16:52] "GET /job/ux%20designer/3 HTTP/1.1" 200 -